Node_World: Node_World.ino File Reference
Node_World.ino File Reference
#include "Arduino.h"
#include "Comms_Manager.h"
#include "Node.h"
#include "DeviceLocator.h"
#include "SoftPWM.h"
#include "EEPROM.h"
#include "DeviceIdentifier.h"
Functions
void blink_out (int num, int delay_time, uint8_t pin)
void blink_out (int num, int delay_time)
void read_EE (uint8_t word, uint8_t *buf, uint8_t offset)
long int read_teensyID ()
void read_dl ()
void setup ()
void node_update ()
void node_go ()
void loop ()
Variables
union {
float f
uint8_t b [4]
} u
static uint8_t teensyID [8]
uint8_t my_id_bytes [3] = {0x00, 0x00, 0x00}
bool serial_registered = false
bool debug = false
bool hacked = false
Comms_Manager network
Node node
DeviceLocator dl
DeviceIdentifier uid_to_type [NUM_UIDS]
Function Documentation
blink_out() [1/2]
void blink_out (int num, int delay_time, uint8_t pin)
A simple debug routine that helps debug what's happening in the code without having access to printlns.
Usage: Put known amount of num, time, pin blink_outs in different places in the code & watch carefully to see what happens.
Hint: Some pins (e.g. 9, 10, among others) are visible on LEDs on the bottom of the Node Controller, so you don't need the full setup to see what's happening. Pin 13 is the on-board LED.
Parameters
num number of times to blink out
delay_time ms to delay between blinks
pin pin number to blink on
Definition at line 42 of file Node_World.ino.
References debug.
Referenced by blink_out(), node_update(), read_dl(), and setup().
blink_out() [2/2]
void blink_out (int num, int delay_time)
Definition at line 56 of file Node_World.ino.
References blink_out().
loop()
void loop ()
Definition at line 876 of file Node_World.ino.
References node_go(), and node_update().
node_go()
void node_go ()
Emulates node.go() in Processing. This isn't inside the Node class to mirror node_update, which can't be in the Node class to avoid sending Comm_manager as a pointer.
Definition at line 842 of file Node_World.ino.
References DR_ARR_SIZE, GE_ARR_SIZE, RebelStar::go(), Moth::go(), DoubleRebelStar::go(), SoundDetector::go(), Actuator::installed, Sensor::installed, MO_RS_ARR_SIZE, Node::my_double_rebel_stars, Node::my_moths, Node::my_rebel_stars, Node::my_sound_detectors, node, SD_ARR_SIZE, and WT_ARR_SIZE.
Referenced by loop().
node_update()
void node_update ()
Mocks node.update() because we didn't want to pass around Comm_Manager as a pointer. Runs every loop to check for mesasges, and act on them based on what the msg code is. At the end of the loop, it clears it's incoming serial buffer so it doesn't fill up and cause a restart.
See Messaging Standards Document for more information about what each message type looks like & does.
Definition at line 270 of file Node_World.ino.
References SoundDetector::autosample, blink_out(), Comms_Manager::clear_serial(), CODE__FADE_ACTUATOR_GROUPS, CODE__INFLUENCE_MAP_GM, CODE__INFLUENCE_MAP_GP, CODE__INFLUENCE_MAP_SD, CODE__INFLUENCE_RANGE_EXM, CODE__INFLUENCE_RANGE_EXP, CODE__INFLUENCE_RANGE_EXS, CODE__INFLUENCE_RANGE_GM, CODE__INFLUENCE_RANGE_GP, CODE__INFLUENCE_RANGE_SD, CODE__PASSWORD, CODE__PING, CODE__SOUND_AUTO_SAMPLING, CODE__SOUND_PT_SAMPLING_CONTROL, CODE__SOUND_PT_SAMPLING_RPI, CODE__SOUND_SET_SAMPLE_FREQUENCY, CODE__SOUND_SET_THRESHOLD, CODE__WAV_MASTER_GAIN, CODE__WAV_PLAY_SOUND, CODE__WAV_TRACK_FADE, CODE__WAV_TRACK_GAIN, DeviceIdentifier::device_number, DeviceIdentifier::device_type, DR_ARR_SIZE, Actuator::EXM_lower, Actuator::EXM_upper, Actuator::EXP_lower, Actuator::EXP_upper, Actuator::EXS_lower, Actuator::EXS_upper, RebelStar::fade(), Moth::fade(), DoubleRebelStar::fade(), SoundDetector::frequency, GE_ARR_SIZE, Comms_Manager::get_message(), Actuator::GM_influence, Actuator::GM_lower, Actuator::GM_upper, Actuator::GP_influence, Actuator::GP_lower, Actuator::GP_upper, Comms_Manager::ID, Actuator::installed, Sensor::installed, Node::isValid(), Comms_Manager::last_code_received, Comms_Manager::last_data_length, Comms_Manager::last_data_received, WAV_Trigger::master_volume_set(), MO_RS_ARR_SIZE, Node::my_double_rebel_stars, my_id_bytes, Node::my_moths, Node::my_rebel_stars, Node::my_sound_detectors, Node::my_wav_triggers, network, node, WAV_Trigger::play_track(), SoundDetector::read_envelope(), SoundDetector::readme, SD_ARR_SIZE, Actuator::SD_influence, Actuator::SD_lower, Actuator::SD_upper, serial_registered, SoundDetector::threshold, WAV_Trigger::track_fade(), WAV_Trigger::track_volume_set(), type_DR, type_MO, type_RS, type_SD, u, uid_to_type, Moth::update(), RebelStar::update(), DoubleRebelStar::update(), SoundDetector::update(), Comms_Manager::write_message(), and WT_ARR_SIZE.
Referenced by loop().
read_dl()
void read_dl ()
Reads the information located in DeviceLocator.h. It's out here instead of being in the DeviceLocator class itself because there were issues with pointers. To avoid using pointers, this function was put out here but eventually, it should be moved into the dl class.
Warning: if the node id isn't found in the DeviceLocator.h, the program will get stuck in this function and start flashing pin 13 with short-short-short-long flashes repeatedly if debug = true.
Definition at line 96 of file Node_World.ino.
References blink_out(), DeviceLocator::configs, DeviceIdentifier::device_number, DeviceIdentifier::device_type, dl, DR_ARR_SIZE, GE_ARR_SIZE, DeviceLocator::HU_uids, DeviceLocator::HU_uids_num, DeviceLocator::HU_uids_types, Actuator::install(), DoubleRebelStar::install(), SoundDetector::install(), WAV_Trigger::install(), MO_RS_ARR_SIZE, Node::my_double_rebel_stars, Node::my_id, Node::my_index, Node::my_moths, Node::my_rebel_stars, Node::my_sound_detectors, Node::my_wav_triggers, DeviceLocator::names, node, DeviceLocator::node_ids, DeviceLocator::node_types, DeviceLocator::num_nodes, NUM_UIDS, SD_ARR_SIZE, Node::total_double_rebel_stars, Node::total_moths, Node::total_rebel_stars, Node::total_sound_detectors, Node::total_wav_triggers, type_DR, type_GE, type_HU, type_MO, type_RS, type_SD, type_UNKNOWN, type_WT, uid_to_type, and WT_ARR_SIZE.
Referenced by setup().
read_EE()
void read_EE (uint8_t word, uint8_t * buf, uint8_t offset)
Low-level function to help get teensy hardware ID
Definition at line 62 of file Node_World.ino.
Referenced by read_teensyID().
read_teensyID()
long int read_teensyID ()
Definition at line 79 of file Node_World.ino.
References my_id_bytes, read_EE(), and teensyID.
Referenced by setup().
setup()
setup ()
The default Arduino setup function, called once at boot.
Definition at line 223 of file Node_World.ino.
References blink_out(), Comms_Manager::clear_serial(), CODE__PASSWORD, Comms_Manager::get_message(), hacked, Comms_Manager::ID, Comms_Manager::last_code_received, Node::my_id, my_id_bytes, network, node, read_dl(), read_teensyID(), serial_registered, and Comms_Manager::write_message().
Variable Documentation
b
uint8_t b[4]
Definition at line 11 of file Node_World.ino.
debug
bool debug = false
Definition at line 17 of file Node_World.ino.
Referenced by blink_out().
dl
DeviceLocator dl
Definition at line 26 of file Node_World.ino.
Referenced by read_dl().
f
float f
Definition at line 10 of file Node_World.ino.
hacked
bool hacked = false
Definition at line 18 of file Node_World.ino.
Referenced by setup().
my_id_bytes
uint8_t my_id_bytes[3] = {0x00, 0x00, 0x00}
Definition at line 15 of file Node_World.ino.
Referenced by node_update(), read_teensyID(), and setup().
network
Comms_Manager network
Definition at line 24 of file Node_World.ino.
Referenced by node_update(), and setup().
node
Node node
Definition at line 25 of file Node_World.ino.
Referenced by node_go(), node_update(), read_dl(), and setup().
serial_registered
bool serial_registered = false
Definition at line 16 of file Node_World.ino.
Referenced by node_update(), and setup().
teensyID
uint8_t teensyID[8] static
Definition at line 14 of file Node_World.ino.
Referenced by read_teensyID().
u
union { ... } u
Referenced by node_update().
uid_to_type
DeviceIdentifier uid_to_type[NUM_UIDS]
Definition at line 28 of file Node_World.ino.
Referenced by node_update(), and read_dl().