Node_World: Comms_Manager Class Reference
Comms_Manager Class Reference
used to communicate over serial with the rpi
#include <Comms_Manager.h>
Public Member Functions
Comms_Manager ()
constructor for the Comms_Manager, sets the baud rate to 57600 by default
Comms_Manager (int baud_rate)
constructor for the Comms_Manager, sets the baud rate to the parameter
~Comms_Manager ()
destructor
void clear_serial ()
clears the serial input buffer
void write_message (uint8_t code)
write an empty message with only the code to the rpi over serial
void write_message (uint8_t msg, uint8_t data[], uint8_t data_length)
write a serial message to the rpi over serial
bool get_message ()
gets the message in the input buffer
Public Attributes
uint8_t last_data_received [MAX_DATA_LENGTH] = { 0 }
int last_data_length
uint8_t last_code_received
uint8_t SOM [2] = {SOM1, SOM2}
uint8_t EOM [2] = {EOM1, EOM2}
uint8_t ID [3] = {0x00, 0x00, 0x00}
bool message_waiting = 0
Detailed Description
used to communicate over serial with the rpi
Author
Adam Francey, Farhan Monower
Definition at line 63 of file Comms_Manager.h.
Constructor & Destructor Documentation
Comms_Manager() [1/2]
Comms_Manager::Comms_Manager ()
constructor for the Comms_Manager, sets the baud rate to 57600 by default
Returns
none
Comms_Manager() [2/2]
Comms_Manager::Comms_Manager (int baud_rate)
constructor for the Comms_Manager, sets the baud rate to the parameter
Parameters
baud_rate the baud rate to set it to
Returns
none
~Comms_Manager()
Comms_Manager::~Comms_Manager ()
destructor
Returns
none
Member Function Documentation
clear_serial()
Comms_Manager::clear_serial ()
clears the serial input buffer
Returns
none
Referenced by node_update(), and setup().
get_message()
Comms_Manager::get_message ()
gets the message in the input buffer
Returns
true if a message if present, false if not
Referenced by node_update(), and setup().
write_message() [1/2]
Comms_Manager::write_message (uint8_t code)
write an empty message with only the code to the rpi over serial
Parameters
code the message code to send
Returns
none
Referenced by node_update(), and setup().
write_message() [2/2]
Comms_Manager::write_message (uint8_t msg, uint8_t data[], uint8_t data_length)
write a serial message to the rpi over serial
Parameters
msg the message code to send
data the array of data values to send
data_length the length of the data array parameter
Returns
none
Member Data Documentation
EOM
Comms_Manager::EOM = {EOM1, EOM2}
array of EOM codes
Definition at line 140 of file Comms_Manager.h.
ID
Comms_Manager::ID = {0x00, 0x00, 0x00}
array of the node ID
Definition at line 145 of file Comms_Manager.h.
Referenced by node_update(), and setup().
last_code_received
Comms_Manager::last_code_received
the code of the last message received
Definition at line 129 of file Comms_Manager.h.
Referenced by node_update(), and setup().
last_data_length
Comms_Manager::last_data_length
array that stores the length of the last_data_received
Definition at line 124 of file Comms_Manager.h.
Referenced by node_update().
last_data_received
Comms_Manager::last_data_received = { 0 }
data array that stores the last data received
Definition at line 119 of file Comms_Manager.h.
Referenced by node_update().
message_waiting
Comms_Manager::message_waiting = 0
is there a message stored and ready to be taken, true if yes, false if no
Definition at line 150 of file Comms_Manager.h.
SOM
Comms_Manager::SOM = {SOM1, SOM2}
array of SOM codes
Definition at line 135 of file Comms_Manager.h.
The documentation for this class was generated from the following file:
Comms_Manager.h