RPi_World: Comm_Manager.pde File Reference
Comm_Manager.pde File Reference
Classes
class Comm_Manager
Handles internal communication between Control, RPi and Nodes.
Variables
int NUM_SOM = 2
message codes for message building
int NUM_EOM = 2
int NUM_ID = 3
int SOM1 = int(0xff)
int EOM1 = int(0xfe)
int CODE__PING = int(0x01)
int CODE__SET_ACTUATOR_VALUES = int(0x1a)
int CODE__SOUND_PT_SAMPLING_CONTROL = int(0x2a)
int CODE__SOUND_PT_SAMPLING_RPI = int(0x2b)
int CODE__SOUND_AUTO_SAMPLING = int(0x2c)
int CODE__SOUND_SET_THRESHOLD = int(0x2d)
int CODE__SOUND_SET_SAMPLE_FREQUENCY = int(0x2e)
int CODE__WAV_PLAY_SOUND = int(0x1b)
int CODE__WAV_MASTER_GAIN = int(0x1c)
int CODE__WAV_TRACK_GAIN = int(0x1d)
int CODE__WAV_TRACK_FADE = int(0x1e)
int CODE__WAV_MASTER_STOP = int(0x1f)
int CODE__INFLUENCE_MAP_GP = int(0Xb1)
int CODE__INFLUENCE_MAP_GM = int(0Xb2)
int CODE__INFLUENCE_MAP_SD = int(0Xb3)
int CODE__INFLUENCE_RANGE_GP = int(0xc1)
int CODE__INFLUENCE_RANGE_GM = int(0xc2)
int CODE__INFLUENCE_RANGE_SD = int(0xc3)
int CODE__INFLUENCE_RANGE_EXP = int(0xc4)
int CODE__INFLUENCE_RANGE_EXM = int(0xc5)
int CODE__INFLUENCE_RANGE_EXS = int(0xc6)
int CODE__PASSWORD = int(0xaa)
byte [] password_array = {byte(0xff), byte(0xff), byte(0x00), byte(0x00), byte(0x00), byte(0x02), byte(0xaa), byte(0x04), byte(0x05), byte(0xfe), byte(0xfe)}
int INDEX_OF_CODE = 6
int node_not_found_sentinel = -99
static boolean SIM = false
static boolean LIVE = true
Variable Documentation
CODE__INFLUENCE_MAP_GM
int CODE__INFLUENCE_MAP_GM = int(0Xb2) package
Definition at line 52 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__INFLUENCE_MAP_GP
int CODE__INFLUENCE_MAP_GP = int(0Xb1) package
Influence map and range codes
Definition at line 51 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__INFLUENCE_MAP_SD
int CODE__INFLUENCE_MAP_SD = int(0Xb3) package
Definition at line 53 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__INFLUENCE_RANGE_EXM
int CODE__INFLUENCE_RANGE_EXM = int(0xc5) package
Definition at line 58 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__INFLUENCE_RANGE_EXP
int CODE__INFLUENCE_RANGE_EXP = int(0xc4) package
Definition at line 57 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__INFLUENCE_RANGE_EXS
int CODE__INFLUENCE_RANGE_EXS = int(0xc6) package
Definition at line 59 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__INFLUENCE_RANGE_GM
int CODE__INFLUENCE_RANGE_GM = int(0xc2) package
Definition at line 55 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__INFLUENCE_RANGE_GP
int CODE__INFLUENCE_RANGE_GP = int(0xc1) package
Definition at line 54 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__INFLUENCE_RANGE_SD
int CODE__INFLUENCE_RANGE_SD = int(0xc3) package
Definition at line 56 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__PASSWORD
int CODE__PASSWORD = int(0xaa) package
password used in hanshaking
Definition at line 63 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_password_to_port().
CODE__PING
int CODE__PING = int(0x01) package
Definition at line 25 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__SET_ACTUATOR_VALUES
int CODE__SET_ACTUATOR_VALUES = int(0x1a) package
used by FADE_ACTUATOR_VALUES to set actuator levels
Definition at line 30 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__SOUND_AUTO_SAMPLING
int CODE__SOUND_AUTO_SAMPLING = int(0x2c) package
Definition at line 36 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__SOUND_PT_SAMPLING_CONTROL
int CODE__SOUND_PT_SAMPLING_CONTROL = int(0x2a) package
Sound sensor codes
Definition at line 34 of file Comm_Manager.pde.
Referenced by Comm_Manager.get_message_real(), and Comm_Manager.write_message().
CODE__SOUND_PT_SAMPLING_RPI
int CODE__SOUND_PT_SAMPLING_RPI = int(0x2b) package
Definition at line 35 of file Comm_Manager.pde.
Referenced by Comm_Manager.get_message_real(), and Comm_Manager.write_message().
CODE__SOUND_SET_SAMPLE_FREQUENCY
int CODE__SOUND_SET_SAMPLE_FREQUENCY = int(0x2e) package
Definition at line 38 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__SOUND_SET_THRESHOLD
int CODE__SOUND_SET_THRESHOLD = int(0x2d) package
Definition at line 37 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__WAV_MASTER_GAIN
int CODE__WAV_MASTER_GAIN = int(0x1c) package
Definition at line 43 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__WAV_MASTER_STOP
int CODE__WAV_MASTER_STOP = int(0x1f) package
Definition at line 46 of file Comm_Manager.pde.
CODE__WAV_PLAY_SOUND
int CODE__WAV_PLAY_SOUND = int(0x1b) package
WAV Trigger codes
Definition at line 42 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__WAV_TRACK_FADE
int CODE__WAV_TRACK_FADE = int(0x1e) package
Definition at line 45 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__WAV_TRACK_GAIN
int CODE__WAV_TRACK_GAIN = int(0x1d) package
Definition at line 44 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
EOM1
int EOM1 = int(0xfe) package
Definition at line 23 of file Comm_Manager.pde.
Referenced by Comm_Manager.get_message_real(), and Comm_Manager.write_message().
INDEX_OF_CODE
INDEX_OF_CODE = 6 package
The array index where the message code for CODE__PASSWORD is contained from the message sent from the node
Definition at line 76 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_password_to_port().
LIVE
LIVE = true static
initialized to true, used by the Control World
Definition at line 99 of file Comm_Manager.pde.
Referenced by Comm_Manager.Comm_Manager().
node_not_found_sentinel
node_not_found_sentinel = -99 package
sentinel value returned when a node is not found in handshaking
Definition at line 82 of file Comm_Manager.pde.
Referenced by Comm_Manager.rpi_build_real_node_map(), and Comm_Manager.write_password_to_port().
NUM_EOM
int NUM_EOM = 2 package
Definition at line 20 of file Comm_Manager.pde.
Referenced by Comm_Manager.get_message_real(), and Comm_Manager.write_message().
NUM_ID
int NUM_ID = 3 package
Definition at line 21 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
NUM_SOM
int NUM_SOM = 2 package
message codes for message building
Definition at line 19 of file Comm_Manager.pde.
Referenced by Comm_Manager.get_message_real(), and Comm_Manager.write_message().
password_array
password_array = {byte(0xff), byte(0xff), byte(0x00), byte(0x00), byte(0x00), byte(0x02), byte(0xaa), byte(0x04), byte(0x05), byte(0xfe), byte(0xfe)} package
array written to nodes during handshaking
Definition at line 70 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_password_to_port().
SIM
SIM = false static
initialized to false, used by the Control World
Definition at line 94 of file Comm_Manager.pde.
SOM1
int SOM1 = int(0xff) package
Definition at line 22 of file Comm_Manager.pde.
Referenced by Comm_Manager.get_message_real(), and Comm_Manager.write_message().