RPi_World: Comm_Manager Class Reference
Comm_Manager Class Reference
Handles internal communication between Control, RPi and Nodes.
Package Functions
Comm_Manager (boolean state, DeviceLocator dev_loc)
Constructor to be used by CONTROL note: the ip address finding code might require editing based on applcation e.g. which_network_type might = "eth1" or = "en0" based on application.
Comm_Manager (DeviceLocator dev_loc)
Constructor to be used by RPI note: the ip address finding code might require editing based on applcation e.g. which_network_type might = "eth1" or = "en0" based on application.
void rpi_build_real_node_map ()
function used to build the node's serial ports map and do handshaking on the rpis
int write_password_to_port (Serial port)
helper function used to do handshaking in rpi_build_real_node_map
void ping_devices ()
part of the heartbeat flow, periodically gets called to ping all attached devices to check if they are alive
void update_heartbeats (long timeout)
part of the heartbeat flow, periodically gets called to check if heartbeats are detected
synchronized void write_message (message_OSC m)
used to communicate with rpis and nodes
synchronized void write_message (String message)
used to communicate with rpis and nodes. Final elseif needs to be commented out on RPi comm manager
synchronized void write_message (String source_address, String destination_address, message_OSC message_in)
used to communicate with rpis and nodes, helper function but can be called publically
synchronized void write_message (String source_address, int destination_address, message_OSC message_in)
synchronized message_OSC get_message_real ()
used to get a real message in the queue. If called on a real rpi, it reads serial ports. Helper function but gets called directly by control only. Skipping over grideye is commented out on the control level.
synchronized message_OSC get_message_virtual (String address)
used to get a virtual message in the queue. Helper function but gets called directly by control only.
synchronized message_OSC get_message (String address)
only called by Pis or Nodes to get messages, if its real it will return a real message
synchronized void osc_received (OscMessage received_message)
helper function called by the osc listener in Control or RPi World.pde
void displayInterfaceInformation (NetworkInterface netint) throws SocketException
helper function used for getting ip addresses
void build_slave_message (String source_address, int destination_address, message_OSC message_in)
Helper function to build slave mode messages (INTENSITIES) [LEGACY, NOT IN USE].
boolean message_check (message_OSC message)
Helper function to check if messages are formatted correctly and have correct information Made according to specs in https://docs.google.com/document/d/1hsEqfDze0vfhwBPVnvVJtoajGdOOtPznUVdY9ZjVoDI/edit RPi comm manager version uses different rpi address checking commands than control.
void print_msg_error (String error, message_OSC message)
Helper function to print an osc message.
Package Attributes
boolean map_built = false
boolean debug = false
boolean use_wifi = false
int osc_port = 4000
int grideye_live_port = 5445
int password_reply_length = 12
int poll_length = 100
int ports_timeout_time = 10000
int serial_port_limit = 64
String my_address = ""
LinkedBlockingQueue< message_OSC > real_received_message_queue = new LinkedBlockingQueue<message_OSC>()
boolean is_live = true
boolean is_real = true
ConcurrentHashMap< String, LinkedBlockingQueue< message_OSC > > virtual_message_map
ConcurrentHashMap< Integer, Serial > my_pis_node_port
ConcurrentHashMap< String, Long > pi_times
ConcurrentHashMap< String, Long > node_times
DeviceLocator device_locator
Detailed Description
Handles internal communication between Control, RPi and Nodes.
Author
Farhan Monower
Definition at line 105 of file Comm_Manager.pde.
Constructor & Destructor Documentation
Comm_Manager() [1/2]
Comm_Manager.Comm_Manager (boolean state, DeviceLocator dev_loc) package
Constructor to be used by CONTROL note: the ip address finding code might require editing based on applcation e.g. which_network_type might = "eth1" or = "en0" based on application.
Parameters
state boolean stating if LIVE or SIM
dev_loc active device locator instance
Returns
none.
Definition at line 201 of file Comm_Manager.pde.
References displayInterfaceInformation(), dl, initialize_osc(), DeviceLocator.is_control_ip(), message_count_this_frame, osc_port, and pi_times.
Comm_Manager() [2/2]
Comm_Manager.Comm_Manager (DeviceLocator dev_loc) package
Constructor to be used by RPI note: the ip address finding code might require editing based on applcation e.g. which_network_type might = "eth1" or = "en0" based on application.
Parameters
dev_loc active device locator instance
Returns
none.
Definition at line 260 of file Comm_Manager.pde.
References device_locator, displayInterfaceInformation(), DeviceLocator.get_network_prefix(), initialize_osc(), DeviceLocator.is_raspberry_pi_ip(), LIVE, message_count_this_frame, node_times, osc_port, and use_wifi.
Member Function Documentation
build_slave_message()
Comm_Manager.build_slave_message (String source_address, int destination_address, message_OSC message_in) package
Helper function to build slave mode messages (INTENSITIES) [LEGACY, NOT IN USE].
Parameters
source_address the source of the message
destination_address the destination address of the message
message_in the osc message to send
Returns
none
Definition at line 1250 of file Comm_Manager.pde.
References message_OSC.get_data(), and write_message().
Referenced by write_message().
displayInterfaceInformation()
Comm_Manager.displayInterfaceInformation (NetworkInterface netint) throws SocketException package
helper function used for getting ip addresses
Author
Matt Gorbet
Parameters
netint Network Interface
Exceptions
SocketException
Returns
none
Definition at line 1233 of file Comm_Manager.pde.
Referenced by Comm_Manager().
get_message()
Comm_Manager.get_message (String address) package
only called by Pis or Nodes to get messages, if its real it will return a real message
Parameters
address the address of the device to check
Returns
a message_OSC
Definition at line 1202 of file Comm_Manager.pde.
References get_message_real(), and get_message_virtual().
Referenced by RPi.run().
get_message_real()
Comm_Manager.get_message_real () package
used to get a real message in the queue. If called on a real rpi, it reads serial ports. Helper function but gets called directly by control only. Skipping over grideye is commented out on the control level.
Returns
a message_OSC
Definition at line 1097 of file Comm_Manager.pde.
References CODE__SOUND_PT_SAMPLING_CONTROL, CODE__SOUND_PT_SAMPLING_RPI, debug, EOM1, grideye_ID, NUM_EOM, NUM_SOM, and SOM1.
Referenced by get_message().
get_message_virtual()
Comm_Manager.get_message_virtual (String address) package
used to get a virtual message in the queue. Helper function but gets called directly by control only.
Parameters
address the address of the virtual device to check
Returns
a message_OSC
Definition at line 1183 of file Comm_Manager.pde.
Referenced by get_message().
message_check()
Comm_Manager.message_check (message_OSC message) package
Helper function to check if messages are formatted correctly and have correct information Made according to specs in https://docs.google.com/document/d/1hsEqfDze0vfhwBPVnvVJtoajGdOOtPznUVdY9ZjVoDI/edit RPi comm manager version uses different rpi address checking commands than control.
Parameters
message the osc message to send
Returns
true if the message is OK, false if it isn't
Definition at line 1290 of file Comm_Manager.pde.
References device_locator, message_OSC.get_code(), message_OSC.get_data(), DeviceLocator.get_names(), DeviceLocator.is_control_ip(), print_msg_error(), and DeviceLocator.rpis.
Referenced by write_message().
osc_received()
Comm_Manager.osc_received (OscMessage received_message) package
helper function called by the osc listener in Control or RPi World.pde
Parameters
received_message the Osc message received
Returns
none
Definition at line 1215 of file Comm_Manager.pde.
Referenced by oscEvent().
ping_devices()
Comm_Manager.ping_devices () package
part of the heartbeat flow, periodically gets called to ping all attached devices to check if they are alive
Returns
none.
Definition at line 429 of file Comm_Manager.pde.
References network, node_times, pi_times, and write_message().
Referenced by RPi.run().
print_msg_error()
Comm_Manager.print_msg_error (String error, message_OSC message) package
Helper function to print an osc message.
Parameters
error the message to display along with the osc message contents
message the osc message to display
Returns
none
Definition at line 2165 of file Comm_Manager.pde.
References message_OSC.get_code(), and message_OSC.get_data().
Referenced by message_check().
rpi_build_real_node_map()
Comm_Manager.rpi_build_real_node_map () package
function used to build the node's serial ports map and do handshaking on the rpis
Returns
none.
Definition at line 338 of file Comm_Manager.pde.
References dl, DeviceLocator.get_node_type(), grideye_ID, node_not_found_sentinel, setup_ports, use_grideye, and write_password_to_port().
Referenced by setup().
update_heartbeats()
Comm_Manager.update_heartbeats (long timeout) package
part of the heartbeat flow, periodically gets called to check if heartbeats are detected
Parameters
timeout a long threshold that if passed, device is declared dead
Returns
none
Definition at line 459 of file Comm_Manager.pde.
References DeviceLocator.get_control_ip(), network, node_times, pi_times, and write_message().
Referenced by RPi.run().
write_message() [1/4]
Comm_Manager.write_message (message_OSC m) package
used to communicate with rpis and nodes
Parameters
m message_OSC to send
Returns
none
Definition at line 493 of file Comm_Manager.pde.
References message_OSC.get_code(), and message_OSC.get_uncut_data().
Referenced by build_slave_message(), draw(), RPi.forward_message_to_node(), ping_devices(), RPi.run(), update_heartbeats(), and write_message().
write_message() [2/4]
Comm_Manager.write_message (String message) package
used to communicate with rpis and nodes. Final elseif needs to be commented out on RPi comm manager
Parameters
message a string with a code and multiple data entries that are space separated
Returns
none
Definition at line 502 of file Comm_Manager.pde.
References message_OSC.get_code(), message_check(), and write_message().
write_message() [3/4]
Comm_Manager.write_message (String source_address, String destination_address, message_OSC message_in) package
used to communicate with rpis and nodes, helper function but can be called publically
Parameters
source_address the source of the message
destination_address the destination of the message
message_in the osc message to send
Returns
none
Definition at line 549 of file Comm_Manager.pde.
References message_OSC.get_OSC(), and internal_comms.
write_message() [4/4]
synchronized void Comm_Manager.write_message (String source_address, int destination_address, message_OSC message_in) package
Send message to a node from control or RPi (real and virtual)
Parameters
source_address the source address of the message
destination_address the node id to send message to
message_in message to send
THE BELOW ELSE STATEMENT IS TO BE COMMENTED OUT ON THE RPI COMMS_MANAGER
Definition at line 585 of file Comm_Manager.pde.
References build_slave_message(), CODE__INFLUENCE_MAP_GM, CODE__INFLUENCE_MAP_GP, CODE__INFLUENCE_MAP_SD, CODE__INFLUENCE_RANGE_EXM, CODE__INFLUENCE_RANGE_EXP, CODE__INFLUENCE_RANGE_EXS, CODE__INFLUENCE_RANGE_GM, CODE__INFLUENCE_RANGE_GP, CODE__INFLUENCE_RANGE_SD, CODE__PING, CODE__SET_ACTUATOR_VALUES, CODE__SOUND_AUTO_SAMPLING, CODE__SOUND_PT_SAMPLING_CONTROL, CODE__SOUND_PT_SAMPLING_RPI, CODE__SOUND_SET_SAMPLE_FREQUENCY, CODE__SOUND_SET_THRESHOLD, CODE__WAV_MASTER_GAIN, CODE__WAV_PLAY_SOUND, CODE__WAV_TRACK_FADE, CODE__WAV_TRACK_GAIN, device_locator, EOM1, DeviceLocator.get_actuator_uid(), message_OSC.get_code(), message_OSC.get_data(), grideye_ID, NUM_EOM, NUM_ID, NUM_SOM, serial_port_limit, and SOM1.
write_password_to_port()
Comm_Manager.write_password_to_port (Serial port) package
helper function used to do handshaking in rpi_build_real_node_map
Parameters
port the Serial port instance to do handshaking with
Returns
an integer node id, or a sentinel value of -99 to show that nothing was found
Definition at line 373 of file Comm_Manager.pde.
References CODE__PASSWORD, INDEX_OF_CODE, node_not_found_sentinel, password_array, password_reply_length, poll_length, and ports_timeout_time.
Referenced by rpi_build_real_node_map().
Member Data Documentation
debug
boolean Comm_Manager.debug = false package
used to do printlns
Definition at line 118 of file Comm_Manager.pde.
Referenced by get_message_real().
device_locator
Comm_Manager.device_locator package
Device locator instance for comm_manager to use
Definition at line 192 of file Comm_Manager.pde.
Referenced by Comm_Manager(), message_check(), and write_message().
grideye_live_port
int Comm_Manager.grideye_live_port = 5445 package
Definition at line 128 of file Comm_Manager.pde.
is_live
boolean Comm_Manager.is_live = true package
/par Logic of real, live, and sim if(this.is_a_Pi) then this.is_real and this.is_live else if (this.is_a_Control && this.is_a_Visualization) then !this.is_real and !this.is_live else if (this.is_a_Control && this.is_live) then !this.is_real and this.is_live
Definition at line 159 of file Comm_Manager.pde.
is_real
boolean Comm_Manager.is_real = true package
Definition at line 160 of file Comm_Manager.pde.
Referenced by RPi.forward_message_to_node().
map_built
Comm_Manager.map_built = false package
state variable used to know if the map is done, not used manually
Definition at line 112 of file Comm_Manager.pde.
Referenced by serialEvent().
my_address
Comm_Manager.my_address = "" package
used by objects to get the current instance's ip address
Definition at line 144 of file Comm_Manager.pde.
Referenced by draw(), and setup().
my_pis_node_port
Comm_Manager.my_pis_node_port package
Used on the pi only, maps a node id to a serial port.
Definition at line 173 of file Comm_Manager.pde.
Referenced by serialEvent().
node_times
Comm_Manager.node_times package
Used on rpi only, keeps track of times for the nodes heartbeats
Definition at line 185 of file Comm_Manager.pde.
Referenced by Comm_Manager(), ping_devices(), and update_heartbeats().
osc_port
int Comm_Manager.osc_port = 4000 package
port allocation
Definition at line 127 of file Comm_Manager.pde.
Referenced by Comm_Manager().
password_reply_length
int Comm_Manager.password_reply_length = 12 package
variables used in handshaking
Definition at line 133 of file Comm_Manager.pde.
Referenced by write_password_to_port().
pi_times
Comm_Manager.pi_times package
Used on control only, keeps track of times for the rpis heartbeats
Definition at line 179 of file Comm_Manager.pde.
Referenced by Comm_Manager(), ping_devices(), and update_heartbeats().
poll_length
int Comm_Manager.poll_length = 100 package
Definition at line 134 of file Comm_Manager.pde.
Referenced by write_password_to_port().
ports_timeout_time
int Comm_Manager.ports_timeout_time = 10000 package
Definition at line 135 of file Comm_Manager.pde.
Referenced by write_password_to_port().
real_received_message_queue
Comm_Manager.real_received_message_queue = new LinkedBlockingQueue<message_OSC>() package
LinkedBlockingQueue object that stores osc messages going to and coming from internal devices (pis and nodes)
Definition at line 151 of file Comm_Manager.pde.
serial_port_limit
int Comm_Manager.serial_port_limit = 64 package
Definition at line 136 of file Comm_Manager.pde.
Referenced by write_message().
use_wifi
boolean Comm_Manager.use_wifi = false package
tells comm manager to use the ethernet or the wifi ip address
Definition at line 123 of file Comm_Manager.pde.
Referenced by Comm_Manager(), and setup().
virtual_message_map
Comm_Manager.virtual_message_map package
Hashmap that stores LinkedBlockingQueues corresponding to each virtual instance of a pi and a node. Stores the virtual messages going to them.
Definition at line 167 of file Comm_Manager.pde.
The documentation for this class was generated from the following file:
Comm_Manager.pde