RPi_World: message_OSC Class Reference
message_OSC Class Reference
Osc wrapper class to OscP5's OscMessage.
Public Member Functions
synchronized String get_code ()
get the code field of the message
synchronized String [] get_data ()
get the data field as an array of strings
synchronized String get_uncut_data ()
get the data field as a string
synchronized void set_code (String code)
sets the code field
synchronized void set_data (String data)
sets the data field
synchronized OscMessage get_OSC ()
gives the contained OscMessage
Protected Attributes
OscMessage message
Package Functions
message_OSC (String code_in, String data_in)
build message using code and data strings
message_OSC (OscMessage received)
build message using an OscMessage
Detailed Description
Osc wrapper class to OscP5's OscMessage.
Author
Farhan Monower
Definition at line 14 of file message_OSC.pde.
Constructor & Destructor Documentation
message_OSC() [1/2]
message_OSC.message_OSC (String code_in, String data_in) package
build message using code and data strings
Parameters
code_in the code string
data_in the data string
Returns
none.
Definition at line 28 of file message_OSC.pde.
message_OSC() [2/2]
message_OSC.message_OSC (OscMessage received) package
build message using an OscMessage
Parameters
received the OscMessage
Returns
none.
Definition at line 38 of file message_OSC.pde.
Member Function Documentation
get_code()
message_OSC.get_code ()
get the code field of the message
Returns
String code.
Definition at line 46 of file message_OSC.pde.
Referenced by RPi.forward_message_to_node(), Comm_Manager.message_check(), Comm_Manager.print_msg_error(), RPi.run(), and Comm_Manager.write_message().
get_data()
message_OSC.get_data ()
get the data field as an array of strings
Returns
string array data
Definition at line 55 of file message_OSC.pde.
Referenced by Comm_Manager.build_slave_message(), Comm_Manager.message_check(), Comm_Manager.print_msg_error(), RPi.run(), and Comm_Manager.write_message().
get_OSC()
message_OSC.get_OSC ()
gives the contained OscMessage
Returns
an OscMessage
Definition at line 91 of file message_OSC.pde.
References message.
Referenced by Comm_Manager.write_message().
get_uncut_data()
message_OSC.get_uncut_data ()
get the data field as a string
Returns
string data
Definition at line 63 of file message_OSC.pde.
Referenced by Comm_Manager.write_message().
set_code()
message_OSC.set_code (String code)
sets the code field
Parameters
code the string to set the code to
Returns
none
Definition at line 73 of file message_OSC.pde.
Referenced by RPi.run().
set_data()
message_OSC.set_data (String data)
sets the data field
Parameters
data the string to set the data to
Returns
none
Definition at line 83 of file message_OSC.pde.
References message.
Member Data Documentation
message
message_OSC.message protected
osc message contained in the class
Definition at line 20 of file message_OSC.pde.
Referenced by get_OSC(), and set_data().
The documentation for this class was generated from the following file:
message_OSC.pde