Control_World: DeviceLocator.pde File Reference
DeviceLocator.pde File Reference
Classes
class DeviceLocator
class DeviceLocatorNodeStorage
class DeviceLocatorControl
class DeviceLocatorNode
Variables
boolean debug = false
int num_GE = 0
int num_SD = 0
static final String [] NO_STRINGS = {}
static final PVector [] NO_POINTS = {}
DeviceLocatorNode dlnode
DeviceLocatorNodeStorage dlnodestorage = new DeviceLocatorNodeStorage()
Variable Documentation
debug
boolean debug = false package
Device Locator
The Device Locator class reads the CSV file to store information about the devices in the sculpture in an easily-accessible format. It also kick starts the device creation process by making Raspberry Pi and Node instances, and provides information to the nodes to help them create actuator/sensor instances.
Author
Niel Mistry et al
Definition at line 12 of file DeviceLocator.pde.
Referenced by DeviceLocator.add_device().
dlnode
DeviceLocatorNode dlnode package
Definition at line 30 of file DeviceLocator.pde.
Referenced by DeviceLocator.add_node(), and DeviceLocator.DeviceLocator().
dlnodestorage
DeviceLocatorNodeStorage dlnodestorage = new DeviceLocatorNodeStorage() package
Definition at line 31 of file DeviceLocator.pde.
Referenced by DeviceLocator.add_device(), DeviceLocator.add_node(), DeviceLocator.generate_dot_h(), DeviceLocator.generate_dot_hexmap(), DeviceLocator.get_actuator_uid(), DeviceLocator.get_configs(), DeviceLocator.get_coordinates(), DeviceLocator.get_coordinates_for_type(), DeviceLocator.get_installed(), DeviceLocator.get_names(), DeviceLocator.get_node_ids(), DeviceLocator.get_node_type(), DeviceLocator.get_num_nodes(), DeviceLocator.get_sensor_uid(), DeviceLocator.get_types(), DeviceLocator.get_uids(), DeviceLocator.node_exists(), and DeviceLocator.node_present().
NO_POINTS
final PVector [] NO_POINTS = {} static private
Definition at line 28 of file DeviceLocator.pde.
NO_STRINGS
final String [] NO_STRINGS = {} static private
Definition at line 27 of file DeviceLocator.pde.
num_GE
int num_GE = 0 package
Definition at line 23 of file DeviceLocator.pde.
Referenced by DeviceLocator.generate_dot_h(), and setup().
num_SD
int num_SD = 0 package
Definition at line 24 of file DeviceLocator.pde.
Referenced by DeviceLocator.generate_dot_h(), and setup().