Control_World: ExcitorBehaviour.pde File Reference
ExcitorBehaviour.pde File Reference
Classes
class ExcitorBehaviour
class Excitor
class ExcitorSystem
class Attractor
class AttractorSystem
Functions
void clearActuatorIntensities ()
void playWavTrigger (int _WTindex, int _wavIndex, int _wavGain)
float getGridEyePresenceAverage ()
Vec3D rotate3D (Vec3D location, float angle, Vec3D axis)
void oscIn (OscMessage theOscMessage)
void sendOmniMasterVolumeToMax ()
Function Documentation
clearActuatorIntensities()
void clearActuatorIntensities () package
Definition at line 417 of file ExcitorBehaviour.pde.
References ExcitorBehaviour.actuatorIntensities, actuatorLocations, and excitorBehaviour.
Referenced by ExcitorBehaviour.run().
getGridEyePresenceAverage()
float getGridEyePresenceAverage () package
Definition at line 447 of file ExcitorBehaviour.pde.
References excitorBehaviour, ExcitorBehaviour.gridEyePresenceMax, and ExcitorBehaviour.gridEyePresences.
oscIn()
void oscIn (OscMessage theOscMessage) package
Definition at line 476 of file ExcitorBehaviour.pde.
References ExcitorSystem.addExcitor(), excitorBehaviour, ExcitorBehaviour.excitorSystem, ExcitorBehaviour.gridEyePresences, and playWavTrigger().
Referenced by oscEvent().
playWavTrigger()
void playWavTrigger (int _WTindex, int _wavIndex, int _wavGain) package
Definition at line 428 of file ExcitorBehaviour.pde.
References control, excitorBehaviour, Control.my_address, network, ExcitorBehaviour.wavTriggerEnabled, and Comm_Manager.write_message().
Referenced by oscIn(), and ExcitorBehaviour.run().
rotate3D()
Vec3D rotate3D (Vec3D location, float angle, Vec3D axis) package
Definition at line 460 of file ExcitorBehaviour.pde.
Referenced by Attractor.update().
sendOmniMasterVolumeToMax()
void sendOmniMasterVolumeToMax () package
Definition at line 508 of file ExcitorBehaviour.pde.
References excitorBehaviour, external_osc, myRemoteLocation, ExcitorBehaviour.omniMasterVolume, and ExcitorBehaviour.prevOmniMasterVolume.
Referenced by ExcitorBehaviour.run().