Control_World: ExcitorSystem Class Reference
ExcitorSystem Class Reference
Public Member Functions
void addExcitor (PVector _location, int _size)
void run ()
Package Functions
ExcitorSystem ()
Package Attributes
ArrayList< Excitor > excitors
Detailed Description
Definition at line 268 of file ExcitorBehaviour.pde.
Constructor & Destructor Documentation
ExcitorSystem()
ExcitorSystem.ExcitorSystem () package
Definition at line 272 of file ExcitorBehaviour.pde.
References excitors.
Member Function Documentation
addExcitor()
void ExcitorSystem.addExcitor (PVector _location, int _size)
Definition at line 276 of file ExcitorBehaviour.pde.
References excitors.
Referenced by ExcitorBehaviour.ExcitorBehaviour(), keyPressed(), oscIn(), and ExcitorBehaviour.run().
run()
void ExcitorSystem.run ()
Definition at line 282 of file ExcitorBehaviour.pde.
References excitors, Excitor.isDead(), and Excitor.run().
Referenced by ExcitorBehaviour.run().
Member Data Documentation
excitors
ArrayList<Excitor> ExcitorSystem.excitors package
Definition at line 270 of file ExcitorBehaviour.pde.
Referenced by addExcitor(), ExcitorSystem(), ExcitorBehaviour.run(), and run().
The documentation for this class was generated from the following file:
ExcitorBehaviour.pde