Control_World: GridEye_Sim Class Reference
GridEye_Sim Class Reference
import"GridEye_Sim.pde";
Package Functions
GridEye_Sim (PApplet p, int port)
void update ()
void go ()
boolean is_prerecorded ()
void setup_prerecorded ()
Package Attributes
int frame
int effectSizeX = 35
int effectSizeY = 40
float nlevel = 2.0
Server gridEyeServer_local
float [] valuesMatrix = new float[64]
String recording_filename = "rightArmWaving.txt"
char recording_rotation = '0'
String [] recording_lines
int recording_index = 0
Detailed Description
\simple simulator for testing GridEye if we don't have one, or for simulating visitor interaction in the sim
Author
PBAI/LASG
Matt Gorbet
Date
December 14 2018
Todo:
create GUI for tweaking all variables!
Definition at line 11 of file GridEye_Sim.pde.
Constructor & Destructor Documentation
GridEye_Sim()
GridEye_Sim.GridEye_Sim (PApplet p, int port) package
Definition at line 27 of file GridEye_Sim.pde.
References prerecorded, and setup_prerecorded().
Member Function Documentation
go()
void GridEye_Sim.go () package
draw mouse effect:
Definition at line 126 of file GridEye_Sim.pde.
References canvash, canvasw, effectSizeX, effectSizeY, frame, prerecorded, recording_index, and valuesMatrix.
Referenced by draw_grideye_panel(), and ge_draw().
is_prerecorded()
boolean GridEye_Sim.is_prerecorded () package
Definition at line 176 of file GridEye_Sim.pde.
References prerecorded.
setup_prerecorded()
void GridEye_Sim.setup_prerecorded () package
Definition at line 180 of file GridEye_Sim.pde.
References recording_filename, recording_index, recording_lines, recording_rotation, setBackground(), and update().
Referenced by GridEye_Sim(), pickfile(), and togglepre().
update()
void GridEye_Sim.update () package
first do noise
Definition at line 40 of file GridEye_Sim.pde.
References canvash, canvasw, effectSizeX, effectSizeY, frame, ge, gridEyeServer_local, nlevel, prerecorded, recording_index, recording_lines, GridEye_Analyzer.setBackground, and valuesMatrix.
Referenced by draw_grideye_panel(), and setup_prerecorded().
Member Data Documentation
effectSizeX
int GridEye_Sim.effectSizeX = 35 package
Definition at line 13 of file GridEye_Sim.pde.
Referenced by go(), and update().
effectSizeY
int GridEye_Sim.effectSizeY = 40 package
Definition at line 14 of file GridEye_Sim.pde.
Referenced by go(), and update().
frame
int GridEye_Sim.frame package
Definition at line 12 of file GridEye_Sim.pde.
Referenced by go(), and update().
gridEyeServer_local
Server GridEye_Sim.gridEyeServer_local package
Definition at line 18 of file GridEye_Sim.pde.
Referenced by update().
nlevel
float GridEye_Sim.nlevel = 2.0 package
Definition at line 16 of file GridEye_Sim.pde.
Referenced by update().
recording_filename
String GridEye_Sim.recording_filename = "rightArmWaving.txt" package
Definition at line 21 of file GridEye_Sim.pde.
Referenced by pickfile(), and setup_prerecorded().
recording_index
int GridEye_Sim.recording_index = 0 package
Definition at line 24 of file GridEye_Sim.pde.
Referenced by go(), setup_prerecorded(), and update().
recording_lines
String [] GridEye_Sim.recording_lines package
Definition at line 23 of file GridEye_Sim.pde.
Referenced by setup_prerecorded(), and update().
recording_rotation
char GridEye_Sim.recording_rotation = '0' package
Definition at line 22 of file GridEye_Sim.pde.
Referenced by draw_grideye_panel(), setRotation(), and setup_prerecorded().
valuesMatrix
float [] GridEye_Sim.valuesMatrix = new float[64] package
Definition at line 19 of file GridEye_Sim.pde.
Referenced by go(), and update().
The documentation for this class was generated from the following file:
GridEye_Sim.pde