Control_World: Control Class Reference
Control Class Reference
Control thread on computer.
Public Member Functions
void run ()
main loop for control, sends and receives messages and does parsing logic
Package Functions
Control ()
Constructor for control.
PVector threed_to_twod (PVector vec)
grideye vector math
float get_grideye_motion_influence (PVector motion, PVector actuator_location, int from_node_id)
MATT -TODO.
synchronized void set_actuator_excitor_influences (ArrayList< Float > actuator_intensities, String excitor_type)
sets the actuator influences with excitors
void kill_all_actuators ()
void run_moth_test ()
runs a test sequence for the moths
void run_dr_test ()
runs a test sequence for the double rebel stars
void run_wt_test ()
runs a test sequence for the wav triggers
void excitorEngineState (boolean state)
MATT - TODO.
Package Attributes
String my_address = ""
int frame = 0
int control_test_message_time = 1
long last_millis
long current_millis
long last_intensity_msg
long ping_time = 10000
long cur_ping_time = 0
long check_time = 30000
long cur_check_time = 0
long timeout_val = 60000
boolean trigger_wav_test = false
boolean fade_wav_test = false
boolean message_send_ramp_up = false
boolean message_send_ramp_down = false
boolean sound_sensor_poll = false
boolean turn_off_auto_sample = false
boolean snapper = false
boolean set_sampling_freq = false
boolean influence_tester = false
boolean kill_all_actuators = false
sets the actuator levels to 0
boolean random_actuator_on = false
boolean begin_grideye_presence = true
boolean mo_test = false
boolean dr_test = false
boolean wt_test = false
boolean sleepmode = false
boolean update_sd_polling = false
boolean update_sd_frequency = false
boolean update_sd_threshold = false
int start_hour = 9
int start_minute = 0
int stop_hour = 21
int stop_minute = 0
int trigger_wav_test_track = 1
int trigger_wav_test_solo = 32
Detailed Description
Control thread on computer.
Control
Control object that creates and sends messages as a control laptop
Author
Matt Gorbet, Et al.
Definition at line 12 of file Control.pde.
Constructor & Destructor Documentation
Control()
Control.Control () package
Constructor for control.
Returns
none.
Definition at line 134 of file Control.pde.
References cur_check_time, cur_ping_time, last_intensity_msg, last_millis, Comm_Manager.my_address, and network.
Member Function Documentation
excitorEngineState()
Control.excitorEngineState (boolean state) package
MATT - TODO.
Parameters
state
Returns
none
Definition at line 716 of file Control.pde.
References excitorBehaviour, ExcitorBehaviour.excitorsInfluenceActive, and ExcitorBehaviour.wavTriggerEnabled.
Referenced by run(), run_dr_test(), run_moth_test(), and run_wt_test().
get_grideye_motion_influence()
Control.get_grideye_motion_influence (PVector motion, PVector actuator_location, int from_node_id) package
MATT -TODO.
Parameters
vec a position vector
Returns
a position vector.
Definition at line 481 of file Control.pde.
References dl, DeviceLocator.get_coordinates_for_type(), and threed_to_twod().
kill_all_actuators()
void Control.kill_all_actuators () package
Definition at line 579 of file Control.pde.
References dl, DeviceLocator.get_all_actuator_coordinates(), and set_actuator_excitor_influences().
Referenced by run(), run_dr_test(), run_moth_test(), and run_wt_test().
run()
Control.run ()
main loop for control, sends and receives messages and does parsing logic
Returns
none.
Definition at line 147 of file Control.pde.
References begin_grideye_presence, check_time, control_test_message_time, cur_check_time, cur_ping_time, dl, dr_test, excitorBehaviour, excitorEngineState(), external_comms, fade_wav_test, DeviceLocator.find_nodes_parent_rpi(), message_OSC.get_code(), message_OSC.get_data(), get_frame(), External_Comms.get_message(), Comm_Manager.get_message_real(), Comm_Manager.get_message_virtual(), DeviceLocator.get_node_type_ids(), DeviceLocator.get_nodes(), DeviceLocator.get_total_num_actuators(), ExcitorBehaviour.gridEyePresences, gui, influence_tester, Comm_Manager.is_live, kill_all_actuators(), last_millis, message_send_ramp_down, message_send_ramp_up, mo_test, my_address, RPi.my_address, network, Comm_Manager.pi_times, Comm_Manager.ping_devices(), ping_time, run_dr_test(), run_moth_test(), run_wt_test(), set_actuator_excitor_influences(), set_sampling_freq, VisGui.show_control_test_1_running, VisGui.show_control_test_2_running, VisGui.show_control_test_3_running, sleepmode, sound_sensor_poll, start_hour, start_minute, stop_hour, stop_messaging, stop_minute, timeout_val, trigger_wav_test, turn_off_auto_sample, Comm_Manager.update_heartbeats(), update_sd_polling, Comm_Manager.write_message(), and wt_test.
run_dr_test()
Control.run_dr_test () package
runs a test sequence for the double rebel stars
Returns
none
Definition at line 634 of file Control.pde.
References dl, Node.DR_ARR_SIZE, dr_test, excitorEngineState(), gui, kill_all_actuators(), network, DeviceLocator.nodes, VisGui.show_control_test_1_running, and Comm_Manager.write_message().
Referenced by run().
run_moth_test()
Control.run_moth_test () package
runs a test sequence for the moths
Returns
none
Definition at line 595 of file Control.pde.
References dl, excitorEngineState(), gui, kill_all_actuators(), Node.MO_RS_ARR_SIZE, mo_test, network, DeviceLocator.nodes, VisGui.show_control_test_2_running, and Comm_Manager.write_message().
Referenced by run().
run_wt_test()
Control.run_wt_test () package
runs a test sequence for the wav triggers
Returns
none
Definition at line 674 of file Control.pde.
References dl, excitorEngineState(), gui, kill_all_actuators(), network, DeviceLocator.nodes, VisGui.show_control_test_3_running, Comm_Manager.write_message(), Node.WT_ARR_SIZE, and wt_test.
Referenced by run().
set_actuator_excitor_influences()
Control.set_actuator_excitor_influences (ArrayList< Float > actuator_intensities, String excitor_type) package
sets the actuator influences with excitors
Parameters
actuator_intensities a list of actuator values to set
excitor_type describes the type of excitor used
Returns
none
Definition at line 505 of file Control.pde.
References dl, network, DeviceLocator.nodes, and Comm_Manager.write_message().
Referenced by kill_all_actuators(), ExcitorBehaviour.run(), and run().
threed_to_twod()
Control.threed_to_twod (PVector vec) package
grideye vector math
Parameters
vec a position vector
Returns
a position vector.
Definition at line 467 of file Control.pde.
Referenced by get_grideye_motion_influence().
Member Data Documentation
begin_grideye_presence
boolean Control.begin_grideye_presence = true package
Definition at line 85 of file Control.pde.
Referenced by keyPressed(), and run().
check_time
long Control.check_time = 30000 package
how often to check the heartbeat, milliseconds
Definition at line 62 of file Control.pde.
Referenced by run().
control_test_message_time
Control.control_test_message_time = 1 package
how many milliseconds inbetween sending messages, at least needs to be 1 to prevent buffer overflow
Definition at line 30 of file Control.pde.
Referenced by run().
cur_check_time
long Control.cur_check_time = 0 package
used to track checking time
Definition at line 66 of file Control.pde.
Referenced by Control(), and run().
cur_ping_time
long Control.cur_ping_time = 0 package
used to track pinging time
Definition at line 57 of file Control.pde.
Referenced by Control(), and run().
current_millis
Control.current_millis package
used for timekeeping in control main loop
Definition at line 42 of file Control.pde.
dr_test
boolean Control.dr_test = false package
Definition at line 88 of file Control.pde.
Referenced by run(), and run_dr_test().
fade_wav_test
boolean Control.fade_wav_test = false package
Definition at line 75 of file Control.pde.
Referenced by keyPressed(), and run().
frame
Control.frame = 0 package
Used in rendering graphics
Definition at line 24 of file Control.pde.
influence_tester
boolean Control.influence_tester = false package
Definition at line 82 of file Control.pde.
Referenced by keyPressed(), and run().
kill_all_actuators
Control.kill_all_actuators = false package
sets the actuator levels to 0
Returns
none
Definition at line 83 of file Control.pde.
Referenced by exit(), and keyPressed().
last_intensity_msg
Control.last_intensity_msg package
used for timekeeping in control main loop
Definition at line 48 of file Control.pde.
Referenced by Control().
last_millis
Control.last_millis package
used for timekeeping in control main loop
Definition at line 36 of file Control.pde.
Referenced by Control(), and run().
message_send_ramp_down
boolean Control.message_send_ramp_down = false package
Definition at line 77 of file Control.pde.
Referenced by keyPressed(), and run().
message_send_ramp_up
boolean Control.message_send_ramp_up = false package
Definition at line 76 of file Control.pde.
Referenced by keyPressed(), and run().
mo_test
boolean Control.mo_test = false package
Definition at line 87 of file Control.pde.
Referenced by run(), and run_moth_test().
my_address
Control.my_address = "" package
stores the address of the control object
Definition at line 18 of file Control.pde.
Referenced by gefwd(), playWavTrigger(), run(), sd_set_freq(), sd_set_polling(), sd_set_threshold(), set_wt_master_gain(), and setBackground().
ping_time
long Control.ping_time = 10000 package
how often to ping, milliseconds
Definition at line 53 of file Control.pde.
Referenced by run().
random_actuator_on
boolean Control.random_actuator_on = false package
Definition at line 84 of file Control.pde.
Referenced by keyPressed().
set_sampling_freq
boolean Control.set_sampling_freq = false package
Definition at line 81 of file Control.pde.
Referenced by keyPressed(), and run().
sleepmode
boolean Control.sleepmode = false package
Definition at line 91 of file Control.pde.
Referenced by run().
snapper
boolean Control.snapper = false package
Definition at line 80 of file Control.pde.
sound_sensor_poll
boolean Control.sound_sensor_poll = false package
Definition at line 78 of file Control.pde.
Referenced by keyPressed(), and run().
start_hour
Control.start_hour = 9 package
operating hours for futurium
Definition at line 102 of file Control.pde.
Referenced by controlEvent(), and run().
start_minute
Control.start_minute = 0 package
operating hours for futurium
Definition at line 107 of file Control.pde.
Referenced by controlEvent(), and run().
stop_hour
Control.stop_hour = 21 package
operating hours for futurium
Definition at line 113 of file Control.pde.
Referenced by controlEvent(), and run().
stop_minute
Control.stop_minute = 0 package
operating hours for futurium
Definition at line 118 of file Control.pde.
Referenced by controlEvent(), and run().
timeout_val
long Control.timeout_val = 60000 package
the time threshold after a device is declared dead if the heartbeat is not detected
Definition at line 71 of file Control.pde.
Referenced by run().
trigger_wav_test
boolean Control.trigger_wav_test = false package
Definition at line 74 of file Control.pde.
Referenced by keyPressed(), and run().
trigger_wav_test_solo
Control.trigger_wav_test_solo = 32 package
testing tracks for WAV trigger
Definition at line 128 of file Control.pde.
trigger_wav_test_track
Control.trigger_wav_test_track = 1 package
testing tracks for WAV trigger
Definition at line 124 of file Control.pde.
turn_off_auto_sample
boolean Control.turn_off_auto_sample = false package
Definition at line 79 of file Control.pde.
Referenced by keyPressed(), and run().
update_sd_frequency
boolean Control.update_sd_frequency = false package
Definition at line 94 of file Control.pde.
update_sd_polling
boolean Control.update_sd_polling = false package
Definition at line 93 of file Control.pde.
Referenced by run().
update_sd_threshold
boolean Control.update_sd_threshold = false package
Definition at line 95 of file Control.pde.
wt_test
boolean Control.wt_test = false package
Definition at line 89 of file Control.pde.
Referenced by run(), and run_wt_test().
The documentation for this class was generated from the following file:
Control.pde