Control_World: DeviceLocator Class Reference
DeviceLocator Class Reference
Public Member Functions
synchronized ArrayList< Integer > get_node_type_ids (String node_type)
synchronized boolean node_exists (int node_id)
synchronized Integer [] get_node_ids ()
synchronized int get_num_nodes ()
synchronized String [] get_types (String node_type)
synchronized int [] get_uids (String node_type)
synchronized PVector [] get_coordinates (int node_id)
synchronized String [] get_names (int node_id)
synchronized String [] get_configs (int node_id)
synchronized boolean [] get_installed (int node_id)
synchronized ArrayList< String > get_rpi_addresses ()
synchronized ArrayList< String > get_node_addresses ()
synchronized int get_moth_index (int moth_number)
synchronized int get_rs_index (int rs_number)
synchronized int get_wt_index (int wt_number)
synchronized int get_actuator_uid (String actuator_type, int actuator_number, int node_id)
synchronized int get_device_index (String type, int number)
synchronized int get_sensor_uid (String sensor_type, int sensor_number, int node_id)
synchronized String get_node_type (int node_id)
Package Functions
DeviceLocator (String file_name)
void createDevices ()
synchronized LinkedHashMap< Integer, Node > get_nodes ()
synchronized LinkedHashMap< String, RPi > get_RPis ()
synchronized String get_control_ip (String rpi_address)
synchronized boolean is_control_ip (String control_ip)
synchronized boolean is_raspberry_pi_ip (String rpi_address)
synchronized String get_network_prefix ()
synchronized RPi find_nodes_parent_rpi (int address)
synchronized ArrayList< Node > find_children_of_RPi (RPi rpi)
synchronized boolean pi_present (String pi_ip)
synchronized boolean node_present (int node_id)
synchronized ArrayList< String > get_all_actuator_types ()
synchronized PVector get_all_actuator_centerpoint ()
synchronized ArrayList< PVector > get_all_actuator_coordinates ()
synchronized int get_total_num_actuators ()
synchronized ArrayList< PVector > get_coordinates_for_type (String type, int node_id)
void generate_dot_h ()
void generate_dot_hexmap ()
Package Attributes
HashSet< String > unique_device_types = new HashSet<String>(Arrays.asList("MO","RS","GE","SD","DR","WT"))
LinkedHashMap< String, RPi > rpis = new LinkedHashMap<String, RPi>()
LinkedHashMap< Integer, Node > nodes = new LinkedHashMap<Integer, Node>()
ArrayList< String > device_index_storage = new ArrayList<String>()
ArrayList< String > unique_node_types = new ArrayList<String>()
ArrayList< String > control_ips = new ArrayList<String>()
int num_actuators = 0
processing.data.Table csv
float [] x_range = new float[2]
float [] y_range = new float[2]
float [] z_range = new float[2]
Private Member Functions
synchronized int convert_uid (String pin)
synchronized boolean add_pi (String name, String pi_ip)
synchronized void add_node (int node_id, String node_type, String rpi_address)
synchronized boolean add_device (String name, String type, int number, int uid, float x, float y, float z, int node_id, boolean inst, String config)
synchronized int get_device_index (String type, int number, boolean installing)
Detailed Description
Definition at line 33 of file DeviceLocator.pde.
Constructor & Destructor Documentation
DeviceLocator()
DeviceLocator.DeviceLocator (String file_name) package
DeviceLocator constructor
Parameters
file_name the name of the CSV file.
Definition at line 70 of file DeviceLocator.pde.
References createDevices(), csv, dlnode, file_name, generate_dot_h(), and generate_dot_hexmap().
Member Function Documentation
add_device()
synchronized boolean DeviceLocator.add_device (String name, String type, int number, int uid, float x, float y, float z, int node_id, boolean inst, String config) private
Adds either an actuator or sensor to the device data structures.
Definition at line 322 of file DeviceLocator.pde.
References DeviceLocatorNodeStorage.all_configs, DeviceLocatorNodeStorage.all_coordinates, DeviceLocatorNodeStorage.all_installed, DeviceLocatorNodeStorage.all_names, DeviceLocatorNodeStorage.all_uid_types, DeviceLocatorNodeStorage.all_uids, debug, device_index_storage, dlnodestorage, get_device_index(), get_node_type(), and num_actuators.
Referenced by createDevices().
add_node()
synchronized void DeviceLocator.add_node (int node_id, String node_type, String rpi_address) private
This function adds the node id and type to the dlnodestorage arrays and then creates a new node object to store in nodes hashmap.
Definition at line 278 of file DeviceLocator.pde.
References dlnode, dlnodestorage, DeviceLocatorNodeStorage.node_ids, DeviceLocatorNodeStorage.node_types, nodes, and rpis.
Referenced by createDevices().
add_pi()
synchronized boolean DeviceLocator.add_pi (String name, String pi_ip) private
Definition at line 266 of file DeviceLocator.pde.
References rpis.
Referenced by createDevices().
convert_uid()
synchronized int DeviceLocator.convert_uid (String pin) private
Handles string to int conversion for pins so that pins like A5 can be used in CSV along with pins like 3. Source of translation for An -> #: https://github.com/PaulStoffregen/cores/blob/master/teensy3/pins_arduino.h
Definition at line 170 of file DeviceLocator.pde.
Referenced by createDevices().
createDevices()
void DeviceLocator.createDevices () package
This function reads the table row-by-row to store data about the various devices in the system. It also kick-starts the device creation process.
Definition at line 83 of file DeviceLocator.pde.
References add_device(), add_node(), add_pi(), control_ips, convert_uid(), csv, node_present(), nodes, pi_present(), unique_node_types, x_range, y_range, and z_range.
Referenced by DeviceLocator().
find_children_of_RPi()
synchronized ArrayList<Node> DeviceLocator.find_children_of_RPi (RPi rpi) package
Definition at line 248 of file DeviceLocator.pde.
References RPi.children_nodes, and nodes.
Referenced by find_nodes_parent_rpi().
find_nodes_parent_rpi()
synchronized RPi DeviceLocator.find_nodes_parent_rpi (int address) package
Definition at line 230 of file DeviceLocator.pde.
References dl, find_children_of_RPi(), nodes, and rpis.
Referenced by gefwd(), Control.run(), setBackground(), GridEye.update_info(), and Comm_Manager.write_message().
generate_dot_h()
void DeviceLocator.generate_dot_h () package
Generates the dot h file from inner structure.
Definition at line 721 of file DeviceLocator.pde.
References DeviceLocatorNodeStorage.all_configs, DeviceLocatorNodeStorage.all_coordinates, DeviceLocatorNodeStorage.all_names, device_index_storage, dlnodestorage, file_name, get_types(), get_uids(), DeviceLocatorNodeStorage.node_ids, DeviceLocatorNodeStorage.node_types, nodes, num_GE, num_SD, unique_device_types, and unique_node_types.
Referenced by DeviceLocator().
generate_dot_hexmap()
void DeviceLocator.generate_dot_hexmap () package
Definition at line 947 of file DeviceLocator.pde.
References dlnodestorage, file_name, DeviceLocatorNodeStorage.node_ids, and DeviceLocatorNodeStorage.node_types.
Referenced by DeviceLocator().
get_actuator_uid()
synchronized int DeviceLocator.get_actuator_uid (String actuator_type, int actuator_number, int node_id)
Returns
The physical uid number that the actuator is connected to for a particular node_id
Definition at line 562 of file DeviceLocator.pde.
References DeviceLocatorNodeStorage.all_uids, dlnodestorage, get_device_index(), and DeviceLocatorNodeStorage.get_node_type().
Referenced by Comm_Manager.write_message().
get_all_actuator_centerpoint()
synchronized PVector DeviceLocator.get_all_actuator_centerpoint () package
Definition at line 649 of file DeviceLocator.pde.
Referenced by setup().
get_all_actuator_coordinates()
synchronized ArrayList<PVector> DeviceLocator.get_all_actuator_coordinates () package
Definition at line 659 of file DeviceLocator.pde.
References nodes.
Referenced by Control.kill_all_actuators(), and setup().
get_all_actuator_types()
synchronized ArrayList<String> DeviceLocator.get_all_actuator_types () package
Definition at line 614 of file DeviceLocator.pde.
References nodes.
Referenced by setup().
get_configs()
synchronized String [] DeviceLocator.get_configs (int node_id)
Definition at line 485 of file DeviceLocator.pde.
References DeviceLocatorNodeStorage.all_configs, and dlnodestorage.
Referenced by DeviceLocatorNode.get_configs().
get_control_ip()
synchronized String DeviceLocator.get_control_ip (String rpi_address) package
Definition at line 188 of file DeviceLocator.pde.
References csv.
Referenced by RPi.run(), and Comm_Manager.update_heartbeats().
get_coordinates()
synchronized PVector [] DeviceLocator.get_coordinates (int node_id)
Returns
A PVector (coordinate) array of the coordinates of the actuators/sensors connected to node_id. The order is the same as the other get_[] functions that return arrays
Definition at line 455 of file DeviceLocator.pde.
References DeviceLocatorNodeStorage.all_coordinates, and dlnodestorage.
Referenced by DeviceLocatorNode.get_coordinates().
get_coordinates_for_type()
synchronized ArrayList<PVector> DeviceLocator.get_coordinates_for_type (String type, int node_id) package
Definition at line 700 of file DeviceLocator.pde.
References DeviceLocatorNodeStorage.all_coordinates, DeviceLocatorNodeStorage.all_uid_types, dlnodestorage, and DeviceLocatorNodeStorage.get_node_type().
Referenced by Control.get_grideye_motion_influence().
get_device_index() [1/2]
synchronized int DeviceLocator.get_device_index (String type, int number, boolean installing) private
Definition at line 569 of file DeviceLocator.pde.
References device_index_storage.
Referenced by add_device(), DeviceLocatorNode.get_actuator_index(), get_actuator_uid(), get_device_index(), get_moth_index(), get_rs_index(), DeviceLocatorNode.get_sensor_index(), get_sensor_uid(), and get_wt_index().
get_device_index() [2/2]
synchronized int DeviceLocator.get_device_index (String type, int number)
Definition at line 588 of file DeviceLocator.pde.
References get_device_index().
get_installed()
synchronized boolean [] DeviceLocator.get_installed (int node_id)
Definition at line 498 of file DeviceLocator.pde.
References DeviceLocatorNodeStorage.all_installed, and dlnodestorage.
get_moth_index()
synchronized int DeviceLocator.get_moth_index (int moth_number)
Definition at line 538 of file DeviceLocator.pde.
References get_device_index().
get_names()
synchronized String [] DeviceLocator.get_names (int node_id)
Returns
A String array of the names the actuators/sensors connected to node_id. The order is the same as the other get_[] functions that return arrays
Definition at line 472 of file DeviceLocator.pde.
References DeviceLocatorNodeStorage.all_names, and dlnodestorage.
Referenced by DeviceLocatorNode.get_arr_len(), DeviceLocatorNode.get_names(), and Comm_Manager.message_check().
get_network_prefix()
synchronized String DeviceLocator.get_network_prefix () package
Definition at line 210 of file DeviceLocator.pde.
References control_ips.
Referenced by Comm_Manager.Comm_Manager().
get_node_addresses()
synchronized ArrayList<String> DeviceLocator.get_node_addresses ()
Definition at line 523 of file DeviceLocator.pde.
References nodes.
Referenced by VisGui.init().
get_node_ids()
synchronized Integer [] DeviceLocator.get_node_ids ()
Definition at line 398 of file DeviceLocator.pde.
References dlnodestorage, and DeviceLocatorNodeStorage.node_ids.
get_node_type()
synchronized String DeviceLocator.get_node_type (int node_id)
Definition at line 602 of file DeviceLocator.pde.
References dlnodestorage, DeviceLocatorNodeStorage.node_ids, and DeviceLocatorNodeStorage.node_types.
Referenced by add_device(), DeviceLocatorNode.get_arr_len(), DeviceLocatorNode.get_types(), and DeviceLocatorNode.get_uids().
get_node_type_ids()
synchronized ArrayList<Integer> DeviceLocator.get_node_type_ids (String node_type)
Definition at line 307 of file DeviceLocator.pde.
References nodes.
Referenced by Control.run(), and set_wt_master_gain().
get_nodes()
synchronized LinkedHashMap<Integer, Node> DeviceLocator.get_nodes () package
Definition at line 155 of file DeviceLocator.pde.
References nodes.
Referenced by Comm_Manager.control_build_virtual_map(), draw(), Control.run(), and setup().
get_num_nodes()
synchronized int DeviceLocator.get_num_nodes ()
Definition at line 412 of file DeviceLocator.pde.
References dlnodestorage, and DeviceLocatorNodeStorage.node_ids.
Referenced by DeviceLocatorNode.get_num_nodes().
get_rpi_addresses()
synchronized ArrayList<String> DeviceLocator.get_rpi_addresses ()
Definition at line 513 of file DeviceLocator.pde.
References rpis.
get_RPis()
synchronized LinkedHashMap<String, RPi> DeviceLocator.get_RPis () package
Definition at line 160 of file DeviceLocator.pde.
References rpis.
Referenced by Comm_Manager.control_build_virtual_map(), draw(), and setup().
get_rs_index()
synchronized int DeviceLocator.get_rs_index (int rs_number)
Definition at line 545 of file DeviceLocator.pde.
References get_device_index().
get_sensor_uid()
synchronized int DeviceLocator.get_sensor_uid (String sensor_type, int sensor_number, int node_id)
Definition at line 593 of file DeviceLocator.pde.
References DeviceLocatorNodeStorage.all_uids, dlnodestorage, get_device_index(), and DeviceLocatorNodeStorage.get_node_type().
get_total_num_actuators()
synchronized int DeviceLocator.get_total_num_actuators () package
Definition at line 695 of file DeviceLocator.pde.
References num_actuators.
Referenced by Control.run().
get_types()
synchronized String [] DeviceLocator.get_types (String node_type)
Returns
A string array of the types of actuators/sensors connected to node_type. The order is the same as the other get_[] functions that return arrays
Definition at line 421 of file DeviceLocator.pde.
References DeviceLocatorNodeStorage.all_uid_types, and dlnodestorage.
Referenced by generate_dot_h(), and DeviceLocatorNode.get_types().
get_uids()
synchronized int [] DeviceLocator.get_uids (String node_type)
Returns
An integer array of the uids of actuators/sensors connected to node_type. The order is the same as the other get_[] functions that return arrays
Definition at line 437 of file DeviceLocator.pde.
References DeviceLocatorNodeStorage.all_uids, and dlnodestorage.
Referenced by generate_dot_h(), and DeviceLocatorNode.get_uids().
get_wt_index()
synchronized int DeviceLocator.get_wt_index (int wt_number)
Definition at line 552 of file DeviceLocator.pde.
References get_device_index().
is_control_ip()
synchronized boolean DeviceLocator.is_control_ip (String control_ip) package
Definition at line 198 of file DeviceLocator.pde.
References control_ips.
Referenced by Comm_Manager.Comm_Manager(), and Comm_Manager.message_check().
is_raspberry_pi_ip()
synchronized boolean DeviceLocator.is_raspberry_pi_ip (String rpi_address) package
Definition at line 202 of file DeviceLocator.pde.
References csv.
Referenced by Comm_Manager.Comm_Manager().
node_exists()
synchronized boolean DeviceLocator.node_exists (int node_id)
Definition at line 392 of file DeviceLocator.pde.
References dlnodestorage, and DeviceLocatorNodeStorage.node_ids.
Referenced by DeviceLocatorNode.node_exists().
node_present()
synchronized boolean DeviceLocator.node_present (int node_id) package
Definition at line 272 of file DeviceLocator.pde.
References dlnodestorage, and DeviceLocatorNodeStorage.node_ids.
Referenced by createDevices().
pi_present()
synchronized boolean DeviceLocator.pi_present (String pi_ip) package
Definition at line 261 of file DeviceLocator.pde.
References rpis.
Referenced by createDevices().
Member Data Documentation
control_ips
ArrayList<String> DeviceLocator.control_ips = new ArrayList<String>() package
Maintains a set [no repeating values] of unique control ip's found - for expandability (possiblity of multiple control computers)
Definition at line 52 of file DeviceLocator.pde.
Referenced by createDevices(), get_network_prefix(), and is_control_ip().
csv
processing.data.Table DeviceLocator.csv package
Definition at line 57 of file DeviceLocator.pde.
Referenced by createDevices(), DeviceLocator(), get_control_ip(), and is_raspberry_pi_ip().
device_index_storage
ArrayList<String> DeviceLocator.device_index_storage = new ArrayList<String>() package
A data structure that stores what combination of Device + Num gets put in what index. Useful for C++ because the size of all the arrays have to be same.
Definition at line 46 of file DeviceLocator.pde.
Referenced by add_device(), generate_dot_h(), and get_device_index().
nodes
LinkedHashMap<Integer, Node> DeviceLocator.nodes = new LinkedHashMap<Integer, Node>() package
A data structure that stores all the Nodes in the sculpture. Guaranteed order (order will be same no matter how many times it's called, important for some of the functionality)
Definition at line 43 of file DeviceLocator.pde.
Referenced by add_node(), createDevices(), find_children_of_RPi(), find_nodes_parent_rpi(), generate_dot_h(), get_all_actuator_coordinates(), get_all_actuator_types(), get_node_addresses(), get_node_type_ids(), get_nodes(), Comm_Manager.message_check(), Control.run_dr_test(), Control.run_moth_test(), Control.run_wt_test(), sd_set_freq(), sd_set_live_or_local(), sd_set_polling(), sd_set_threshold(), Control.set_actuator_excitor_influences(), and set_wt_master_gain().
num_actuators
int DeviceLocator.num_actuators = 0 package
Number of actuators
Definition at line 55 of file DeviceLocator.pde.
Referenced by add_device(), and get_total_num_actuators().
rpis
LinkedHashMap<String, RPi> DeviceLocator.rpis = new LinkedHashMap<String, RPi>() package
A data structure that stores all the Raspberry Pis in the sculpture. Guaranteed order (order will be same no matter how many times it's called, important for some of the functionality)
Definition at line 39 of file DeviceLocator.pde.
Referenced by add_node(), add_pi(), find_nodes_parent_rpi(), get_rpi_addresses(), get_RPis(), Comm_Manager.message_check(), and pi_present().
unique_device_types
HashSet<String> DeviceLocator.unique_device_types = new HashSet<String>(Arrays.asList("MO","RS","GE","SD","DR","WT")) package
Definition at line 35 of file DeviceLocator.pde.
Referenced by generate_dot_h().
unique_node_types
ArrayList<String> DeviceLocator.unique_node_types = new ArrayList<String>() package
Maintains a list of the unique node types (this one just makes sense!)
Definition at line 49 of file DeviceLocator.pde.
Referenced by createDevices(), and generate_dot_h().
x_range
float [] DeviceLocator.x_range = new float[2] package
Definition at line 60 of file DeviceLocator.pde.
Referenced by createDevices().
y_range
float [] DeviceLocator.y_range = new float[2] package
Definition at line 61 of file DeviceLocator.pde.
Referenced by createDevices().
z_range
float [] DeviceLocator.z_range = new float[2] package
Definition at line 62 of file DeviceLocator.pde.
Referenced by createDevices().
The documentation for this class was generated from the following file:
DeviceLocator.pde