Control_World: RPi Class Reference
RPi Class Reference
RPi object.
Public Member Functions
void run ()
the main loop for the RPi thread
Package Functions
RPi (String ip, String name)
constructor for the RPi
synchronized void forward_message_to_node (message_OSC message_to_forward)
forwards message if the message is not meant for the pi, helper function
synchronized void configure_grideye (String[] params)
MATT - TODO.
void go ()
does nothing at the moment, abstracted
Package Attributes
String pi_id
String my_address
boolean debug = false
long ping_time = 10000
long cur_ping_time = 0
long cur_check_time = 0
long check_time = 30000
long timeout_val = 60000
ArrayList< Integer > children_nodes = new ArrayList<Integer>()
Detailed Description
RPi object.
RPi
Virtual RPi object
Author
Matt Gorbet et al
Definition at line 13 of file RPi.pde.
Constructor & Destructor Documentation
RPi()
RPi.RPi (String ip, String name) package
constructor for the RPi
Parameters
ip the ip address of the RPi
name the name of the RPi
Returns
none
Definition at line 61 of file RPi.pde.
References my_address, and pi_id.
Member Function Documentation
configure_grideye()
RPi.configure_grideye (String [] params) package
MATT - TODO.
Parameters
params
Returns
none
Definition at line 162 of file RPi.pde.
References frameskip, ge, interestThreshold, GridEye_Analyzer.motion_threshold, noiseThreshold, overall_relax, GridEye_Analyzer.polling_frequency, and GridEye_Analyzer.presence_threshold.
Referenced by run().
forward_message_to_node()
RPi.forward_message_to_node (message_OSC message_to_forward) package
forwards message if the message is not meant for the pi, helper function
Parameters
message_to_forward the message to forward
Returns
none
Definition at line 149 of file RPi.pde.
References message_OSC.get_code(), Comm_Manager.is_real, network, and Comm_Manager.write_message().
Referenced by run().
go()
RPi.go () package
does nothing at the moment, abstracted
Returns
none
Definition at line 186 of file RPi.pde.
Referenced by draw().
run()
RPi.run ()
the main loop for the RPi thread
Returns
none
Definition at line 75 of file RPi.pde.
References check_time, configure_grideye(), cur_check_time, cur_ping_time, debug, dl, forward_message_to_node(), GridEye_Analyzer.forward_stream_to_control, ge, message_OSC.get_code(), DeviceLocator.get_control_ip(), message_OSC.get_data(), Comm_Manager.get_message(), network, Comm_Manager.ping_devices(), ping_time, message_OSC.set_code(), GridEye_Analyzer.setBackground, timeout_val, Comm_Manager.update_heartbeats(), and Comm_Manager.write_message().
Member Data Documentation
check_time
long RPi.check_time = 30000 package
how frequently it checks for heartbeat
Definition at line 45 of file RPi.pde.
Referenced by run().
children_nodes
ArrayList<Integer> RPi.children_nodes = new ArrayList<Integer>() package
Definition at line 52 of file RPi.pde.
Referenced by DeviceLocator.find_children_of_RPi().
cur_check_time
long RPi.cur_check_time = 0 package
keep track of check time
Definition at line 41 of file RPi.pde.
Referenced by run().
cur_ping_time
long RPi.cur_ping_time = 0 package
keep track of ping time
Definition at line 37 of file RPi.pde.
Referenced by run().
debug
RPi.debug = false package
choose whether or not to generate printlns for testing
Definition at line 28 of file RPi.pde.
Referenced by run().
my_address
RPi.my_address package
the ip of the Pi
Definition at line 23 of file RPi.pde.
Referenced by Comm_Manager.control_build_virtual_map(), gefwd(), RPi(), Control.run(), setBackground(), GridEye.update_info(), and Comm_Manager.write_message().
pi_id
RPi.pi_id package
the name of the pi
Definition at line 18 of file RPi.pde.
Referenced by RPi().
ping_time
long RPi.ping_time = 10000 package
how frequently it pings
Definition at line 33 of file RPi.pde.
Referenced by run().
timeout_val
long RPi.timeout_val = 60000 package
what time is required for it to be pronounced timed out
Definition at line 49 of file RPi.pde.
Referenced by run().
The documentation for this class was generated from the following file:
RPi.pde