Control_World: GridEye Class Reference
GridEye Class Reference
Package Functions
GridEye ()
void install (String n, PVector pos, int p, Node parent_, DeviceIdentifier des, String config_string)
float readValue ()
void update ()
boolean parse_config_string (String config_string)
synchronized void go ()
void update_info ()
void draw_me (boolean mouseover)
Package Functions inherited from Sensor
Sensor ()
Constructor for the sensor class.
void install (String n, PVector pos, int p, Node parent_, DeviceIdentifier des)
function called to initialize and virtually "install" the sensor
abstract float readValue ()
Get this sensor's reading. Abstracted so other classes an expand upon it.
abstract boolean parse_config_string (String config)
void update ()
used to do any regular action for the device
void go ()
In processing, used for visualization of the device.
synchronized void draw_to_screen ()
used to draw the device onto visualization
void draw_box ()
MATT - TODO.
PVector [] getBox ()
MATT - TODO.
boolean is_mouse_over ()
MATT - TODO.
boolean containsPoint (PVector[] verts, float px, float py)
used for picking inside a bounding box – taken from: http://hg.postspectacular.com/toxiclibs/src/tip/src.core/toxi/geom/Polygon2D.java
void draw_me (boolean mouseover)
MATT - TODO.
void update_info ()
MATT - TODO.
Package Attributes
int DEFAULT_THRESHOLD = 30
int DEFAULT_FREQ = 5
int threshold = DEFAULT_THRESHOLD
int frequency = DEFAULT_FREQ
boolean readme = false
int last_millis = millis()
int elapsed_millis = 0
boolean reading_live_data = true
Client gridEyeClient_live
Package Attributes inherited from Sensor
String name
float cur_value
PVector position
int uid
boolean installed
Node parent = null
DeviceIdentifier designator
int virtual_width
int virtual_height
int virtual_depth
Additional Inherited Members
Protected Member Functions inherited from Sensor
int get_num_commands (String str)
MATT - TODO.
String get_full_command (String str, int num)
MATT - TODO.
String [] get_command (String str, int num)
MATT - TODO.
Detailed Description
Definition at line 1 of file GridEye.pde.
Constructor & Destructor Documentation
GridEye()
GridEye.GridEye () package
Definition at line 16 of file GridEye.pde.
Member Function Documentation
draw_me()
void GridEye.draw_me (boolean mouseover) package
Definition at line 168 of file GridEye.pde.
References all_sensors_selected, Sensor.designator, DeviceIdentifier.device_type, drawgui, selected_sensor, Sensor.virtual_height, and Sensor.virtual_width.
go()
synchronized void GridEye.go () package
Definition at line 125 of file GridEye.pde.
References Sensor.draw_to_screen().
Referenced by Node.go().
install()
void GridEye.install (String n, PVector pos, int p, Node parent_, DeviceIdentifier des, String config_string) package
Definition at line 20 of file GridEye.pde.
References elapsed_millis, last_millis, parse_config_string(), Sensor.virtual_depth, Sensor.virtual_height, and Sensor.virtual_width.
Referenced by Node.read_dl().
parse_config_string()
boolean GridEye.parse_config_string (String config_string) package
Definition at line 78 of file GridEye.pde.
References Sensor.get_command(), and Sensor.get_num_commands().
Referenced by install().
readValue()
float GridEye.readValue () package
Definition at line 44 of file GridEye.pde.
update()
void GridEye.update () package
Definition at line 52 of file GridEye.pde.
References elapsed_millis, frequency, and last_millis.
Referenced by Node.run().
update_info()
void GridEye.update_info () package
Definition at line 137 of file GridEye.pde.
References dl, DeviceLocator.find_nodes_parent_rpi(), ge, Comm_Manager.grideye_live_port, VisGui.gridEyeClient_live, gui, RPi.my_address, Sensor.name, network, VisGui.open_ge_client(), selected_sensor, and VisGui.update_ge_panel().
Member Data Documentation
DEFAULT_FREQ
int GridEye.DEFAULT_FREQ = 5 package
Definition at line 4 of file GridEye.pde.
DEFAULT_THRESHOLD
int GridEye.DEFAULT_THRESHOLD = 30 package
Definition at line 3 of file GridEye.pde.
elapsed_millis
int GridEye.elapsed_millis = 0 package
Definition at line 10 of file GridEye.pde.
Referenced by install(), and update().
frequency
int GridEye.frequency = DEFAULT_FREQ package
Definition at line 7 of file GridEye.pde.
Referenced by update().
gridEyeClient_live
Client GridEye.gridEyeClient_live package
Definition at line 14 of file GridEye.pde.
last_millis
int GridEye.last_millis = millis() package
Definition at line 9 of file GridEye.pde.
Referenced by install(), and update().
reading_live_data
boolean GridEye.reading_live_data = true package
Definition at line 12 of file GridEye.pde.
readme
boolean GridEye.readme = false package
Definition at line 8 of file GridEye.pde.
threshold
int GridEye.threshold = DEFAULT_THRESHOLD package
Definition at line 6 of file GridEye.pde.
The documentation for this class was generated from the following file:
GridEye.pde