Control_World: ExcitorBehaviour Class Reference
ExcitorBehaviour Class Reference
Package Functions
ExcitorBehaviour ()
void run ()
Package Attributes
boolean excitorsInfluenceActive = true
boolean backroundBehaviourEnabled = true
boolean showExcitors = true
boolean showAttractors = true
boolean wavTriggerEnabled = true
ArrayList< PVector > actuatorLocations = dl.get_all_actuator_coordinates()
ArrayList< String > actuatorTypes = dl.get_all_actuator_types()
ArrayList< Float > actuatorIntensities = new ArrayList<Float>(actuatorLocations.size())
boolean excitorTriggerGateOpen = true
float excitorTriggerThreshold = 0.5
boolean wavTriggerGateOpen = true
float wavTriggerThreshold = 0.3
float gridEyePresenceMax
ExcitorSystem excitorSystem
int excitorCount = 0
float excitorSpeedLimit = 3
AttractorSystem attractorSystem
int attractorCount = 6
float attractorForce = 0.2
float attractorSpeedLimit = 3
float centerForce = -0.1
float [] soundDetectorValues = new float[5]
float [] gridEyePresences = new float[dl.get_node_type_ids("GN").size()]
int backBehaviourLastTimeTriggered
int wavTriggerLastTimeTriggered
boolean omniMasterMute
float omniMasterVolume
float prevOmniMasterVolume
Detailed Description
Definition at line 10 of file ExcitorBehaviour.pde.
Constructor & Destructor Documentation
ExcitorBehaviour()
ExcitorBehaviour.ExcitorBehaviour () package
Definition at line 54 of file ExcitorBehaviour.pde.
References actuatorIntensities, actuatorLocations, AttractorSystem.addAttractor(), ExcitorSystem.addExcitor(), attractorCount, attractorSystem, excitorCount, and excitorSystem.
Member Function Documentation
run()
void ExcitorBehaviour.run () package
Definition at line 76 of file ExcitorBehaviour.pde.
References actuatorIntensities, ExcitorSystem.addExcitor(), attractorSystem, backBehaviourLastTimeTriggered, backroundBehaviourEnabled, clearActuatorIntensities(), control, excitorBehaviour, ExcitorSystem.excitors, excitorsInfluenceActive, excitorSystem, excitorTriggerGateOpen, excitorTriggerThreshold, gridEyePresenceMax, gridEyePresences, playWavTrigger(), ExcitorSystem.run(), AttractorSystem.run(), sendOmniMasterVolumeToMax(), Control.set_actuator_excitor_influences(), wavTriggerLastTimeTriggered, and wavTriggerThreshold.
Referenced by draw().
Member Data Documentation
actuatorIntensities
ArrayList<Float> ExcitorBehaviour.actuatorIntensities = new ArrayList<Float>(actuatorLocations.size()) package
Definition at line 22 of file ExcitorBehaviour.pde.
Referenced by clearActuatorIntensities(), ExcitorBehaviour(), run(), and Excitor.setActuatorDistanceIntensities().
actuatorLocations
ArrayList<PVector> ExcitorBehaviour.actuatorLocations = dl.get_all_actuator_coordinates() package
Definition at line 20 of file ExcitorBehaviour.pde.
Referenced by ExcitorBehaviour(), and Excitor.setActuatorDistanceIntensities().
actuatorTypes
ArrayList<String> ExcitorBehaviour.actuatorTypes = dl.get_all_actuator_types() package
Definition at line 21 of file ExcitorBehaviour.pde.
attractorCount
int ExcitorBehaviour.attractorCount = 6 package
Definition at line 38 of file ExcitorBehaviour.pde.
Referenced by Excitor.applyAtrractorForceSingle(), and ExcitorBehaviour().
attractorForce
float ExcitorBehaviour.attractorForce = 0.2 package
Definition at line 39 of file ExcitorBehaviour.pde.
Referenced by Excitor.applyAtrractorForceSingle(), and keyPressed().
attractorSpeedLimit
float ExcitorBehaviour.attractorSpeedLimit = 3 package
Definition at line 40 of file ExcitorBehaviour.pde.
attractorSystem
AttractorSystem ExcitorBehaviour.attractorSystem package
Definition at line 37 of file ExcitorBehaviour.pde.
Referenced by Excitor.applyAtrractorForceSingle(), AttractorSystem.display(), ExcitorBehaviour(), and run().
backBehaviourLastTimeTriggered
int ExcitorBehaviour.backBehaviourLastTimeTriggered package
Definition at line 49 of file ExcitorBehaviour.pde.
Referenced by run().
backroundBehaviourEnabled
boolean ExcitorBehaviour.backroundBehaviourEnabled = true package
Definition at line 14 of file ExcitorBehaviour.pde.
Referenced by run().
centerForce
float ExcitorBehaviour.centerForce = -0.1 package
Definition at line 43 of file ExcitorBehaviour.pde.
Referenced by Excitor.applyCenterForce().
excitorCount
int ExcitorBehaviour.excitorCount = 0 package
Definition at line 33 of file ExcitorBehaviour.pde.
Referenced by ExcitorBehaviour().
excitorsInfluenceActive
boolean ExcitorBehaviour.excitorsInfluenceActive = true package
Definition at line 13 of file ExcitorBehaviour.pde.
Referenced by Control.excitorEngineState(), run(), and Excitor.setActuatorDistanceIntensities().
excitorSpeedLimit
float ExcitorBehaviour.excitorSpeedLimit = 3 package
Definition at line 34 of file ExcitorBehaviour.pde.
Referenced by Excitor.update().
excitorSystem
ExcitorSystem ExcitorBehaviour.excitorSystem package
Definition at line 32 of file ExcitorBehaviour.pde.
Referenced by ExcitorBehaviour(), keyPressed(), oscIn(), and run().
excitorTriggerGateOpen
boolean ExcitorBehaviour.excitorTriggerGateOpen = true package
Definition at line 25 of file ExcitorBehaviour.pde.
Referenced by run().
excitorTriggerThreshold
float ExcitorBehaviour.excitorTriggerThreshold = 0.5 package
Definition at line 26 of file ExcitorBehaviour.pde.
Referenced by run().
gridEyePresenceMax
float ExcitorBehaviour.gridEyePresenceMax package
Definition at line 29 of file ExcitorBehaviour.pde.
Referenced by getGridEyePresenceAverage(), and run().
gridEyePresences
float [] ExcitorBehaviour.gridEyePresences = new float[dl.get_node_type_ids("GN").size()] package
Definition at line 46 of file ExcitorBehaviour.pde.
Referenced by getGridEyePresenceAverage(), oscIn(), run(), and Control.run().
omniMasterMute
boolean ExcitorBehaviour.omniMasterMute package
Definition at line 51 of file ExcitorBehaviour.pde.
omniMasterVolume
float ExcitorBehaviour.omniMasterVolume package
Definition at line 52 of file ExcitorBehaviour.pde.
Referenced by controlEvent(), and sendOmniMasterVolumeToMax().
prevOmniMasterVolume
float ExcitorBehaviour.prevOmniMasterVolume package
Definition at line 52 of file ExcitorBehaviour.pde.
Referenced by sendOmniMasterVolumeToMax().
showAttractors
boolean ExcitorBehaviour.showAttractors = true package
Definition at line 16 of file ExcitorBehaviour.pde.
Referenced by Attractor.run(), and AttractorSystem.run().
showExcitors
boolean ExcitorBehaviour.showExcitors = true package
Definition at line 15 of file ExcitorBehaviour.pde.
Referenced by Excitor.run().
soundDetectorValues
float [] ExcitorBehaviour.soundDetectorValues = new float[5] package
Definition at line 45 of file ExcitorBehaviour.pde.
wavTriggerEnabled
boolean ExcitorBehaviour.wavTriggerEnabled = true package
Definition at line 17 of file ExcitorBehaviour.pde.
Referenced by Control.excitorEngineState(), and playWavTrigger().
wavTriggerGateOpen
boolean ExcitorBehaviour.wavTriggerGateOpen = true package
Definition at line 27 of file ExcitorBehaviour.pde.
wavTriggerLastTimeTriggered
int ExcitorBehaviour.wavTriggerLastTimeTriggered package
Definition at line 49 of file ExcitorBehaviour.pde.
Referenced by run().
wavTriggerThreshold
float ExcitorBehaviour.wavTriggerThreshold = 0.3 package
Definition at line 28 of file ExcitorBehaviour.pde.
Referenced by run().
The documentation for this class was generated from the following file:
ExcitorBehaviour.pde