Control_World: Moth Class Reference
Moth Class Reference
Package Functions
Moth ()
synchronized void install (String n, PVector pos, int p, Node parent, DeviceIdentifier des)
synchronized void update ()
void setValue (int v)
void fade (int v, long fade_millis)
boolean parse_config_string (String str)
synchronized void go ()
void update_info ()
void draw_me (boolean mouseover)
void moth_star (float x, float y, float radius1, float radius2, int npoints)
Package Functions inherited from Actuator
Actuator ()
void install (String n, PVector pos, int pin, Node parent_, DeviceIdentifier des)
abstract void setValue (int v)
abstract void fade (int v, long fade_millis)
DInt setValue (int v, DInt cur_values)
DInt fade (int v, long fade_millis, DInt cur_values)
DInt update_DInt (DInt cur_values)
abstract void update ()
synchronized void go ()
synchronized void draw_to_screen ()
void draw_box ()
PVector [] getBox ()
boolean is_mouse_over ()
boolean containsPoint (PVector[] verts, float px, float py)
void draw_me (boolean mouseover)
void update_info ()
Package Attributes
DInt cur_values = new DInt(200)
Package Attributes inherited from Actuator
String name
DeviceIdentifier designator
int uid
int cur_value
boolean installed = false
int virtual_width
int virtual_height
int virtual_depth
PVector position
boolean selected = false
Node parent
Additional Inherited Members
Protected Member Functions inherited from Actuator
int get_num_commands (String str)
String get_full_command (String str, int num)
String [] get_command (String str, int num)
Detailed Description
Moth
Moth object for visualization
Author
Matt Gorbet, Et al.
Definition at line 10 of file Moth.pde.
Constructor & Destructor Documentation
Moth()
Moth.Moth () package
Definition at line 14 of file Moth.pde.
Member Function Documentation
draw_me()
void Moth.draw_me (boolean mouseover) package
Definition at line 77 of file Moth.pde.
References ALL_NODES_SELECTED, cur_values, Actuator.designator, DeviceIdentifier.device_type, drawgui, get_frame(), moth_star(), Node.node_id, Actuator.parent, selected_actuator, selected_node, DInt.state, Actuator.virtual_height, and Actuator.virtual_width.
fade()
void Moth.fade (int v, long fade_millis) package
Definition at line 37 of file Moth.pde.
References cur_values.
Referenced by Node.run(), and setValue().
go()
synchronized void Moth.go () package
Definition at line 48 of file Moth.pde.
References Actuator.draw_to_screen().
Referenced by Node.go().
install()
synchronized void Moth.install (String n, PVector pos, int p, Node parent, DeviceIdentifier des) package
Definition at line 19 of file Moth.pde.
References Actuator.parent, Actuator.virtual_depth, Actuator.virtual_height, and Actuator.virtual_width.
Referenced by Node.read_dl().
moth_star()
void Moth.moth_star (float x, float y, float radius1, float radius2, int npoints) package
Definition at line 99 of file Moth.pde.
References cur_values, get_frame(), and DInt.state.
Referenced by draw_me().
parse_config_string()
boolean Moth.parse_config_string (String str) package
Definition at line 42 of file Moth.pde.
setValue()
void Moth.setValue (int v) package
Definition at line 33 of file Moth.pde.
References cur_values, fade(), and DInt.max_value.
update()
synchronized void Moth.update () package
Definition at line 27 of file Moth.pde.
References Actuator.cur_value, cur_values, DInt.state, and Actuator.update_DInt().
Referenced by Node.run().
update_info()
void Moth.update_info () package
Definition at line 59 of file Moth.pde.
References VisGui.actuator_settings, VisGui.actuatorChart, apply_moth_settings_to(), Actuator.cur_value, gui, VisGui.moth_settings, selected_actuator, and VisGui.which_moths.
Member Data Documentation
cur_values
DInt Moth.cur_values = new DInt(200) package
Definition at line 12 of file Moth.pde.
Referenced by draw_me(), fade(), moth_star(), setValue(), and update().
The documentation for this class was generated from the following file:
Moth.pde