Control_World: DeviceLocatorNode Class Reference
DeviceLocatorNode Class Reference
Package Functions
DeviceLocatorNode (DeviceLocator dl)
int get_num_nodes ()
int get_arr_len (int node_id)
String [] get_types (int node_id)
int [] get_uids (int node_id)
PVector [] get_coordinates (int node_id)
String [] get_names (int node_id)
String [] get_configs (int node_id)
boolean node_exists (int node_id)
int get_actuator_index (String act_type, int act_num)
int get_sensor_index (String sen_type, int sen_num)
Package Attributes
DeviceLocator dl
Detailed Description
This is a helper class that helps translate the complicated dl information into arrays that the node can work with
Definition at line 1047 of file DeviceLocator.pde.
Constructor & Destructor Documentation
DeviceLocatorNode()
DeviceLocatorNode.DeviceLocatorNode (DeviceLocator dl) package
Definition at line 1051 of file DeviceLocator.pde.
References dl.
Member Function Documentation
get_actuator_index()
int DeviceLocatorNode.get_actuator_index (String act_type, int act_num) package
Definition at line 1101 of file DeviceLocator.pde.
References dl, and DeviceLocator.get_device_index().
get_arr_len()
int DeviceLocatorNode.get_arr_len (int node_id) package
Definition at line 1061 of file DeviceLocator.pde.
References dl, DeviceLocator.get_names(), and DeviceLocator.get_node_type().
Referenced by Node.read_dl().
get_configs()
String [] DeviceLocatorNode.get_configs (int node_id) package
Definition at line 1091 of file DeviceLocator.pde.
References dl, and DeviceLocator.get_configs().
Referenced by Node.read_dl().
get_coordinates()
PVector [] DeviceLocatorNode.get_coordinates (int node_id) package
Definition at line 1081 of file DeviceLocator.pde.
References dl, and DeviceLocator.get_coordinates().
Referenced by Node.read_dl().
get_names()
String [] DeviceLocatorNode.get_names (int node_id) package
Definition at line 1086 of file DeviceLocator.pde.
References dl, and DeviceLocator.get_names().
Referenced by Node.read_dl().
get_num_nodes()
int DeviceLocatorNode.get_num_nodes () package
Definition at line 1056 of file DeviceLocator.pde.
References dl, and DeviceLocator.get_num_nodes().
get_sensor_index()
int DeviceLocatorNode.get_sensor_index (String sen_type, int sen_num) package
Definition at line 1106 of file DeviceLocator.pde.
References dl, and DeviceLocator.get_device_index().
get_types()
String [] DeviceLocatorNode.get_types (int node_id) package
Definition at line 1069 of file DeviceLocator.pde.
References dl, DeviceLocator.get_node_type(), and DeviceLocator.get_types().
Referenced by Node.read_dl().
get_uids()
int [] DeviceLocatorNode.get_uids (int node_id) package
Definition at line 1075 of file DeviceLocator.pde.
References dl, DeviceLocator.get_node_type(), and DeviceLocator.get_uids().
Referenced by Node.read_dl().
node_exists()
boolean DeviceLocatorNode.node_exists (int node_id) package
Definition at line 1096 of file DeviceLocator.pde.
References dl, and DeviceLocator.node_exists().
Referenced by Node.read_dl().
Member Data Documentation
dl
DeviceLocator DeviceLocatorNode.dl package
Definition at line 1049 of file DeviceLocator.pde.
Referenced by DeviceLocatorNode(), get_actuator_index(), get_arr_len(), get_configs(), get_coordinates(), get_names(), get_num_nodes(), get_sensor_index(), get_types(), get_uids(), and node_exists().
The documentation for this class was generated from the following file:
DeviceLocator.pde