Control_World: Actuator Class Reference
Actuator Class Reference abstract
superclass for actuators, all actuators inherit from this.
import"Actuator.pde";
Protected Member Functions
int get_num_commands (String str)
String get_full_command (String str, int num)
String [] get_command (String str, int num)
Package Functions
Actuator ()
void install (String n, PVector pos, int pin, Node parent_, DeviceIdentifier des)
abstract void setValue (int v)
abstract void fade (int v, long fade_millis)
DInt setValue (int v, DInt cur_values)
DInt fade (int v, long fade_millis, DInt cur_values)
DInt update_DInt (DInt cur_values)
abstract void update ()
synchronized void go ()
synchronized void draw_to_screen ()
void draw_box ()
PVector [] getBox ()
boolean is_mouse_over ()
boolean containsPoint (PVector[] verts, float px, float py)
void draw_me (boolean mouseover)
void update_info ()
Package Attributes
String name
DeviceIdentifier designator
int uid
int cur_value
boolean installed = false
int virtual_width
int virtual_height
int virtual_depth
PVector position
boolean selected = false
Node parent
Static Private Attributes
static final char CONFIG_DELIMITER = ';'
Detailed Description
superclass for actuators, all actuators inherit from this.
Author
PBAI/LASG
Adam Francey
Matt Gorbet
Niel Mistry
Date
February 20 2019
Todo:
{ stop passing pin_mode - all actuator pins should be outputs anyway; change initialization to match C++ class }
Definition at line 12 of file Actuator.pde.
Constructor & Destructor Documentation
Actuator()
Actuator.Actuator () package
Default constructor, used to instantiate empty Actuator instances
Definition at line 36 of file Actuator.pde.
References designator, installed, name, parent, position, and uid.
Member Function Documentation
containsPoint()
boolean Actuator.containsPoint (PVector [] verts, float px, float py) package
Definition at line 305 of file Actuator.pde.
Referenced by is_mouse_over().
draw_box()
void Actuator.draw_box () package
@ MATT - TODO
Definition at line 257 of file Actuator.pde.
References cam, and getBox().
Referenced by draw_to_screen().
draw_me()
void Actuator.draw_me (boolean mouseover) package
@ MATT - TODO
Definition at line 329 of file Actuator.pde.
References virtual_height, and virtual_width.
Referenced by draw_to_screen().
draw_to_screen()
synchronized void Actuator.draw_to_screen () package
@MATT - TODO
Definition at line 182 of file Actuator.pde.
References VisGui.actuatorChart, billboard_mode, cam, draw_bounding_boxes, draw_box(), draw_me(), drawgui, gui, is_mouse_over(), keyshift, name, Node.node_id, over_actuator, position, select_item, selected_actuator, textheight, textoffset, and update_info().
Referenced by RebelStar.go(), Moth.go(), go(), and WAV_Trigger.go().
fade() [1/2]
abstract void Actuator.fade (int v, long fade_millis) abstract package
Required function that lets software fade the value over time. Needs to be written for every actuator.
Parameters
v The value to fade to.
fade_millis The amount of time (ms) to reach value v.
Referenced by setValue().
fade() [2/2]
DInt Actuator.fade (int v, long fade_millis, DInt cur_values) package
A utility class to fade a DInt over some time (see DInt page for more information about DInts)
Parameters
v The value to fade to.
fade_millis The amount of time (ms) to reach value v.
cur_values The DInt to edit.
Definition at line 98 of file Actuator.pde.
References DInt.fade_delta, DInt.fade_direction, DInt.fade_duration, DInt.fade_percent_done, DInt.fade_start, DInt.fade_target, DInt.last_millis, and DInt.state.
get_command()
String [] Actuator.get_command (String str, int num) protected
Gets the combination of keyword and arguments, stored in an array as {keyword, arguments}.
Parameters
str The config string
num Which index of command you want to get from it
Definition at line 401 of file Actuator.pde.
References get_full_command().
Referenced by DoubleRebelStar.parse_config_string(), and WAV_Trigger.parse_config_string().
get_full_command()
String Actuator.get_full_command (String str, int num) protected
Gets a full command (keyword + arguments) from a config string
Parameters
str The config string
num The index of command that you want from the config string.
Definition at line 366 of file Actuator.pde.
References CONFIG_DELIMITER.
Referenced by get_command().
get_num_commands()
int Actuator.get_num_commands (String str) protected
Gets the number of commands from a config string.
Parameters
str Incoming config string
Definition at line 350 of file Actuator.pde.
References CONFIG_DELIMITER.
Referenced by DoubleRebelStar.parse_config_string(), and WAV_Trigger.parse_config_string().
getBox()
PVector [] Actuator.getBox () package
@ MATT - TODO Gets the bounding box for rollovers?
Definition at line 275 of file Actuator.pde.
References virtual_height, and virtual_width.
Referenced by draw_box(), and is_mouse_over().
go()
synchronized void Actuator.go () package
The go function gets called every iteration to update the drawing on the screen. This also needs to be written for every Actuator sub-class to provide Actuator specific behaviour.
Definition at line 169 of file Actuator.pde.
References draw_to_screen().
install()
void Actuator.install (String n, PVector pos, int pin, Node parent_, DeviceIdentifier des) package
Install function, used to initialize actuators.
Parameters
n Name of actuator
pos A vector describing this actuator's position
pin One of the pins on this actuator, this acts as a unique identifier for the actuator (a way to address it)
parent_ A node object that is this actuator's parent (what it's connected to)
des A DeviceIdentifier object that stores the two letter identifier and what # this actuator is. For example "MO" and 2
Definition at line 55 of file Actuator.pde.
References designator, installed, name, parent, position, uid, virtual_depth, virtual_height, and virtual_width.
is_mouse_over()
boolean Actuator.is_mouse_over () package
Definition at line 298 of file Actuator.pde.
References containsPoint(), and getBox().
Referenced by draw_to_screen().
setValue() [1/2]
abstract void Actuator.setValue (int v) abstract package
Required function that lets software set this actuator's value to something. Needs to be written for each actuator.
Parameters
v The target value to set to.
setValue() [2/2]
DInt Actuator.setValue (int v, DInt cur_values) package
A utility class that sets the value of a DInt (see DInt page for more information)
Parameters
v The value to set to.
cur_values The DInt to edit.
Definition at line 87 of file Actuator.pde.
References fade().
update()
abstract void Actuator.update () abstract package
An update function that gets called every iteration. Needs to be written for each actuator's unique behaviours
update_DInt()
DInt Actuator.update_DInt (DInt cur_values) package
A utility class to update a DInt's internal variables. This get's called every iteration.
Parameters
cur_values The DInt to update.
Definition at line 123 of file Actuator.pde.
References DInt.elapsed_millis, DInt.fade_delta, DInt.fade_direction, DInt.fade_duration, DInt.fade_minimum_interval, DInt.fade_percent_done, DInt.fade_start, DInt.last_millis, DInt.max_value, DInt.run_time, DInt.start_time, and DInt.state.
Referenced by Moth.update(), RebelStar.update(), DoubleRebelStar.update(), and WAV_Trigger.update().
update_info()
void Actuator.update_info () package
@ MATT - TODO
Definition at line 336 of file Actuator.pde.
References VisGui.actuatorChart, cur_value, gui, and selected_actuator.
Referenced by draw_to_screen().
Member Data Documentation
CONFIG_DELIMITER
final char Actuator.CONFIG_DELIMITER = ';' static private
Definition at line 13 of file Actuator.pde.
Referenced by get_full_command(), and get_num_commands().
cur_value
int Actuator.cur_value package
Definition at line 18 of file Actuator.pde.
Referenced by WAV_Trigger.draw_me(), Moth.update(), RebelStar.update(), Moth.update_info(), and update_info().
designator
DeviceIdentifier Actuator.designator package
Definition at line 16 of file Actuator.pde.
Referenced by Actuator(), Moth.draw_me(), DoubleRebelStar.draw_me(), and install().
installed
boolean Actuator.installed = false package
Definition at line 20 of file Actuator.pde.
Referenced by Actuator(), install(), and Node.run().
name
String Actuator.name package
Definition at line 15 of file Actuator.pde.
Referenced by Actuator(), draw_to_screen(), install(), DoubleRebelStar.update_info(), and WAV_Trigger.update_info().
parent
Node Actuator.parent package
Definition at line 31 of file Actuator.pde.
Referenced by Actuator(), apply_actuator_settings_to(), Moth.draw_me(), DoubleRebelStar.draw_me(), Moth.install(), RebelStar.install(), and install().
position
PVector Actuator.position package
Definition at line 26 of file Actuator.pde.
Referenced by Actuator(), draw_to_screen(), and install().
selected
boolean Actuator.selected = false package
Definition at line 28 of file Actuator.pde.
uid
int Actuator.uid package
Definition at line 17 of file Actuator.pde.
Referenced by Actuator(), and install().
virtual_depth
int Actuator.virtual_depth package
Definition at line 24 of file Actuator.pde.
Referenced by Moth.install(), RebelStar.install(), DoubleRebelStar.install(), install(), WAV_Trigger.install(), and RebelStar.RebelStar().
virtual_height
int Actuator.virtual_height package
Definition at line 23 of file Actuator.pde.
Referenced by Moth.draw_me(), DoubleRebelStar.draw_me(), draw_me(), getBox(), Moth.install(), RebelStar.install(), DoubleRebelStar.install(), install(), WAV_Trigger.install(), and RebelStar.RebelStar().
virtual_width
int Actuator.virtual_width package
Definition at line 22 of file Actuator.pde.
Referenced by RebelStar.draw_me(), Moth.draw_me(), DoubleRebelStar.draw_me(), WAV_Trigger.draw_me(), draw_me(), getBox(), Moth.install(), RebelStar.install(), DoubleRebelStar.install(), install(), WAV_Trigger.install(), and RebelStar.RebelStar().
The documentation for this class was generated from the following file:
Actuator.pde