Control_World: WAV_Trigger Class Reference
WAV_Trigger Class Reference
The virtual wav trigger class.
Static Public Attributes
static final int MAX_TRACKS = 14
static final int MAX_VOL = 80
Package Functions
void install (String n, PVector pos, int pin, Node parent_, DeviceIdentifier des, String config)
installs the wav trigger actuator into the visualzation
WAV_Trigger ()
constructor for the wav trigger
boolean parse_config_string (String config)
void update ()
used to keep track of playing audio simulation
void setValue (int v)
Vestigial function from the actuator class. Needed to be overloaded. NOT TO BE CALLED, currently just does a master gain fade.
void fade (int v, long fade_millis)
used to fade the audio dints
void play_track (String track_num, boolean solo)
play a track solo or poly
void master_volume_set (int vol)
used to set the master volume
void track_volume_set (String trk, int vol)
used to set the volume of a track alone
void track_fade (String trk, int vol, long time, boolean stop)
used to fade the volume of a track alone, and stop it if required
long find_track_length (String track_num)
java code that finds the length of the .wav file in the local directory
synchronized void go ()
used to draw the wav trigger in the visualization
void draw_me (boolean mouseover)
draw to visualization if the mouse is over this actuator
synchronized void update_info ()
send data to visualization
Package Functions inherited from Actuator
Actuator ()
void install (String n, PVector pos, int pin, Node parent_, DeviceIdentifier des)
abstract void setValue (int v)
abstract void fade (int v, long fade_millis)
DInt setValue (int v, DInt cur_values)
DInt fade (int v, long fade_millis, DInt cur_values)
DInt update_DInt (DInt cur_values)
abstract void update ()
synchronized void go ()
synchronized void draw_to_screen ()
void draw_box ()
PVector [] getBox ()
boolean is_mouse_over ()
boolean containsPoint (PVector[] verts, float px, float py)
void draw_me (boolean mouseover)
void update_info ()
Package Attributes
String [] tracks = new String[MAX_TRACKS]
DInt [] volumes = new DInt[MAX_TRACKS]
boolean [] stop_tracks = new boolean[MAX_TRACKS]
int default_volume = 70
DInt master_volume = new DInt(MAX_VOL)
int runtime = 2000
int txpin
int rxpin
boolean playing = false
Package Attributes inherited from Actuator
String name
DeviceIdentifier designator
int uid
int cur_value
boolean installed = false
int virtual_width
int virtual_height
int virtual_depth
PVector position
boolean selected = false
Node parent
Additional Inherited Members
Protected Member Functions inherited from Actuator
int get_num_commands (String str)
String get_full_command (String str, int num)
String [] get_command (String str, int num)
Detailed Description
The virtual wav trigger class.
Definition at line 16 of file WAV_Trigger.pde.
Constructor & Destructor Documentation
WAV_Trigger()
WAV_Trigger.WAV_Trigger () package
constructor for the wav trigger
Returns
none
Definition at line 101 of file WAV_Trigger.pde.
Member Function Documentation
draw_me()
WAV_Trigger.draw_me (boolean mouseover) package
draw to visualization if the mouse is over this actuator
Parameters
mouseover boolean that says if the mouse is over the actuator
Returns
none
Definition at line 317 of file WAV_Trigger.pde.
References Actuator.cur_value, get_frame(), playing, and Actuator.virtual_width.
fade()
WAV_Trigger.fade (int v, long fade_millis) package
used to fade the audio dints
Parameters
v the volume to set it to
fade_millis the milliseconds to fade it
Returns
none
Definition at line 189 of file WAV_Trigger.pde.
References MAX_TRACKS, and volumes.
Referenced by Node.run(), setValue(), and track_fade().
find_track_length()
WAV_Trigger.find_track_length (String track_num) package
java code that finds the length of the .wav file in the local directory
Parameters
track_num the track to find the length of
Returns
long time in milliseconds of the track length
Definition at line 277 of file WAV_Trigger.pde.
References base_path.
Referenced by play_track().
go()
WAV_Trigger.go () package
used to draw the wav trigger in the visualization
Returns
none
Definition at line 301 of file WAV_Trigger.pde.
References Actuator.draw_to_screen().
Referenced by Node.go().
install()
WAV_Trigger.install (String n, PVector pos, int pin, Node parent_, DeviceIdentifier des, String config) package
installs the wav trigger actuator into the visualzation
Parameters
n name of the wav trigger
pos the position of the wav trigger
pin the pin/uid of the wav trigger
des the device identifier for the 2 character 1 number identifier e.g. WV1
config the configuration string for the wav trigger
Returns
none
Definition at line 86 of file WAV_Trigger.pde.
References parse_config_string(), rxpin, txpin, Actuator.virtual_depth, Actuator.virtual_height, and Actuator.virtual_width.
Referenced by Node.read_dl().
master_volume_set()
WAV_Trigger.master_volume_set (int vol) package
used to set the master volume
Parameters
vol the volume
Returns
none
Definition at line 229 of file WAV_Trigger.pde.
References setValue().
parse_config_string()
boolean WAV_Trigger.parse_config_string (String config) package
Definition at line 112 of file WAV_Trigger.pde.
References Actuator.get_command(), Actuator.get_num_commands(), runtime, rxpin, and txpin.
Referenced by install().
play_track()
WAV_Trigger.play_track (String track_num, boolean solo) package
play a track solo or poly
Parameters
track_num the track to play. Should be a numerical value.
solo if true play the track solo (turn off other tracks playing), if false play the track poly (do not turn off other tracks playing)
Returns
none
Definition at line 203 of file WAV_Trigger.pde.
References default_volume, find_track_length(), MAX_TRACKS, MAX_VOL, setValue(), stop_tracks, tracks, and volumes.
setValue()
WAV_Trigger.setValue (int v) package
Vestigial function from the actuator class. Needed to be overloaded. NOT TO BE CALLED, currently just does a master gain fade.
Returns
none
Definition at line 178 of file WAV_Trigger.pde.
References fade().
Referenced by master_volume_set(), play_track(), and track_volume_set().
track_fade()
WAV_Trigger.track_fade (String trk, int vol, long time, boolean stop) package
used to fade the volume of a track alone, and stop it if required
Parameters
trk the track to adjust
vol the volume to set it to
time the milliseconds to keep fading it
stop true if you want to stop the track, false otherwise
Returns
none
Definition at line 258 of file WAV_Trigger.pde.
References fade(), MAX_TRACKS, stop_tracks, tracks, and volumes.
track_volume_set()
WAV_Trigger.track_volume_set (String trk, int vol) package
used to set the volume of a track alone
Parameters
trk the track to adjust
vol the volume to set it to
Returns
none
Definition at line 240 of file WAV_Trigger.pde.
References MAX_TRACKS, setValue(), tracks, and volumes.
update()
WAV_Trigger.update () package
used to keep track of playing audio simulation
Returns
none
Definition at line 154 of file WAV_Trigger.pde.
References MAX_TRACKS, playing, stop_tracks, tracks, Actuator.update_DInt(), and volumes.
Referenced by Node.run().
update_info()
WAV_Trigger.update_info () package
send data to visualization
Returns
none
Definition at line 351 of file WAV_Trigger.pde.
References VisGui.actuatorChart, get_frame(), gui, MAX_TRACKS, Actuator.name, playing, selected_actuator, tracks, and volumes.
Member Data Documentation
default_volume
WAV_Trigger.default_volume = 70 package
70, translates to 0dB unity gain on the node level
Definition at line 47 of file WAV_Trigger.pde.
Referenced by play_track().
master_volume
WAV_Trigger.master_volume = new DInt(MAX_VOL) package
the main gain of the wav trigger, scales the other volumes by this value. Similar to a computer's volume mixer.
Definition at line 52 of file WAV_Trigger.pde.
MAX_TRACKS
WAV_Trigger.MAX_TRACKS = 14 static
constant value, spec'd to the WAV Trigger's physical channel limitation
Definition at line 21 of file WAV_Trigger.pde.
Referenced by fade(), play_track(), track_fade(), track_volume_set(), update(), and update_info().
MAX_VOL
WAV_Trigger.MAX_VOL = 80 static
constant value, spec'd to the WAV Trigger's physical gain limitation. The actual values it takes is from 10 to -70dB, we translate this on the node level.
Definition at line 26 of file WAV_Trigger.pde.
Referenced by play_track().
playing
WAV_Trigger.playing = false package
boolean to let control know if wav trigger is actively playing audio
Definition at line 74 of file WAV_Trigger.pde.
Referenced by draw_me(), update(), and update_info().
runtime
WAV_Trigger.runtime = 2000 package
the default run time, 2s. Gets set automatically to track length using a java file search.
Definition at line 58 of file WAV_Trigger.pde.
Referenced by parse_config_string().
rxpin
WAV_Trigger.rxpin package
one of the pins of the wav trigger
Definition at line 68 of file WAV_Trigger.pde.
Referenced by install(), and parse_config_string().
stop_tracks
WAV_Trigger.stop_tracks = new boolean[MAX_TRACKS] package
array that keeps track of the which tracks to stop
Definition at line 42 of file WAV_Trigger.pde.
Referenced by play_track(), track_fade(), and update().
tracks
WAV_Trigger.tracks = new String[MAX_TRACKS] package
array that keeps track of the playing tracks
Definition at line 32 of file WAV_Trigger.pde.
Referenced by play_track(), track_fade(), track_volume_set(), update(), and update_info().
txpin
WAV_Trigger.txpin package
one of the pins of the wav trigger
Definition at line 68 of file WAV_Trigger.pde.
Referenced by install(), and parse_config_string().
volumes
WAV_Trigger.volumes = new DInt[MAX_TRACKS] package
array that keeps track of the playing track volumes
Definition at line 37 of file WAV_Trigger.pde.
Referenced by fade(), play_track(), track_fade(), track_volume_set(), update(), and update_info().
The documentation for this class was generated from the following file:
WAV_Trigger.pde