Control_World: RebelStar Class Reference
RebelStar Class Reference
Package Functions
RebelStar ()
synchronized void install (String n, PVector pos, int p, Node parent, DeviceIdentifier des)
synchronized void update ()
void setValue (int v)
void fade (int v, long fade_millis)
boolean parse_config_string (String str)
synchronized void go ()
void draw_me (boolean mouseover)
Package Functions inherited from Actuator
Actuator ()
void install (String n, PVector pos, int pin, Node parent_, DeviceIdentifier des)
abstract void setValue (int v)
abstract void fade (int v, long fade_millis)
DInt setValue (int v, DInt cur_values)
DInt fade (int v, long fade_millis, DInt cur_values)
DInt update_DInt (DInt cur_values)
abstract void update ()
synchronized void go ()
synchronized void draw_to_screen ()
void draw_box ()
PVector [] getBox ()
boolean is_mouse_over ()
boolean containsPoint (PVector[] verts, float px, float py)
void draw_me (boolean mouseover)
void update_info ()
Package Attributes
DInt cur_values = new DInt()
Package Attributes inherited from Actuator
String name
DeviceIdentifier designator
int uid
int cur_value
boolean installed = false
int virtual_width
int virtual_height
int virtual_depth
PVector position
boolean selected = false
Node parent
Additional Inherited Members
Protected Member Functions inherited from Actuator
int get_num_commands (String str)
String get_full_command (String str, int num)
String [] get_command (String str, int num)
Detailed Description
RebelStar
RebelStar object for visualization
Author
Matt Gorbet, Et al.
Definition at line 8 of file RebelStar.pde.
Constructor & Destructor Documentation
RebelStar()
RebelStar.RebelStar () package
Definition at line 12 of file RebelStar.pde.
References Actuator.virtual_depth, Actuator.virtual_height, and Actuator.virtual_width.
Member Function Documentation
draw_me()
void RebelStar.draw_me (boolean mouseover) package
Definition at line 57 of file RebelStar.pde.
References cur_values, drawgui, selected_actuator, DInt.state, and Actuator.virtual_width.
fade()
void RebelStar.fade (int v, long fade_millis) package
Definition at line 37 of file RebelStar.pde.
References cur_values.
Referenced by Node.run().
go()
synchronized void RebelStar.go () package
Definition at line 47 of file RebelStar.pde.
References Actuator.draw_to_screen().
Referenced by Node.go().
install()
synchronized void RebelStar.install (String n, PVector pos, int p, Node parent, DeviceIdentifier des) package
Definition at line 20 of file RebelStar.pde.
References Actuator.parent, Actuator.virtual_depth, Actuator.virtual_height, and Actuator.virtual_width.
Referenced by Node.read_dl().
parse_config_string()
boolean RebelStar.parse_config_string (String str) package
Definition at line 42 of file RebelStar.pde.
setValue()
void RebelStar.setValue (int v) package
Definition at line 33 of file RebelStar.pde.
References cur_values, and DInt.max_value.
update()
synchronized void RebelStar.update () package
Definition at line 28 of file RebelStar.pde.
References Actuator.cur_value, cur_values, DInt.state, and Actuator.update_DInt().
Referenced by Node.run().
Member Data Documentation
cur_values
DInt RebelStar.cur_values = new DInt() package
Definition at line 10 of file RebelStar.pde.
Referenced by draw_me(), fade(), setValue(), and update().
The documentation for this class was generated from the following file:
RebelStar.pde