Control_World: SoundDetector Class Reference
SoundDetector Class Reference
Processing sensor class to create virtual Sound Detector extending Sensor.
Package Functions
SoundDetector ()
default constructor for the Sound Detector
void install (String n, PVector pos, int p, Node parent_, DeviceIdentifier des, String config_string)
Used to install the sound detector into the visualization.
float readValue ()
returns the sound reading from your computer's mic
int read_envelope ()
supposed to read the envelope pin, currently just calls the readValue() function
int read_audio ()
supposed to read the audio pin, currently just calls the readValue() function. Not really implemented yet.
boolean is_triggered ()
checks if the current reading is above the specified threshold
void update ()
called to update the detector and check if its time for polling
boolean parse_config_string (String config_string)
synchronized void go ()
on Processing, sends messages back to control and updates visualization
void update_info ()
helper function to do drawing of visualization
void draw_me (boolean mouseover)
does drawing if the sensor was moused over
Package Functions inherited from Sensor
Sensor ()
Constructor for the sensor class.
void install (String n, PVector pos, int p, Node parent_, DeviceIdentifier des)
function called to initialize and virtually "install" the sensor
abstract float readValue ()
Get this sensor's reading. Abstracted so other classes an expand upon it.
abstract boolean parse_config_string (String config)
void update ()
used to do any regular action for the device
void go ()
In processing, used for visualization of the device.
synchronized void draw_to_screen ()
used to draw the device onto visualization
void draw_box ()
MATT - TODO.
PVector [] getBox ()
MATT - TODO.
boolean is_mouse_over ()
MATT - TODO.
boolean containsPoint (PVector[] verts, float px, float py)
used for picking inside a bounding box – taken from: http://hg.postspectacular.com/toxiclibs/src/tip/src.core/toxi/geom/Polygon2D.java
void draw_me (boolean mouseover)
MATT - TODO.
void update_info ()
MATT - TODO.
Package Attributes
int DEFAULT_THRESHOLD = 5
int DEFAULT_FREQ = 50
int p_envelope = 0
int p_audio = 0
int threshold = DEFAULT_THRESHOLD
int frequency = DEFAULT_FREQ
boolean readme = false
int last_millis = millis()
int elapsed_millis = 0
boolean autosample = true
boolean use_local = false
boolean push_value = false
Amplitude my_level
Package Attributes inherited from Sensor
String name
float cur_value
PVector position
int uid
boolean installed
Node parent = null
DeviceIdentifier designator
int virtual_width
int virtual_height
int virtual_depth
Additional Inherited Members
Protected Member Functions inherited from Sensor
int get_num_commands (String str)
MATT - TODO.
String get_full_command (String str, int num)
MATT - TODO.
String [] get_command (String str, int num)
MATT - TODO.
Detailed Description
Processing sensor class to create virtual Sound Detector extending Sensor.
SoundDetector
Sound Detector class
Author
Farhan Monower, Matt Gorbet
Farhan Monower
Definition at line 13 of file SoundDetector.pde.
Constructor & Destructor Documentation
SoundDetector()
SoundDetector.SoundDetector () package
default constructor for the Sound Detector
Returns
none
Definition at line 96 of file SoundDetector.pde.
Member Function Documentation
draw_me()
SoundDetector.draw_me (boolean mouseover) package
does drawing if the sensor was moused over
Parameters
moseover true if was moused over else false
Returns
none
Definition at line 350 of file SoundDetector.pde.
References all_sensors_selected, Sensor.designator, DeviceIdentifier.device_type, drawgui, selected_sensor, Sensor.virtual_height, and Sensor.virtual_width.
go()
SoundDetector.go () package
on Processing, sends messages back to control and updates visualization
Returns
none
Definition at line 252 of file SoundDetector.pde.
References Sensor.cur_value, Sensor.draw_to_screen(), network, Node.node_id, Sensor.parent, push_value, readme, readValue(), selected_sensor, threshold, use_local, and Comm_Manager.write_message().
Referenced by Node.go().
install()
SoundDetector.install (String n, PVector pos, int p, Node parent_, DeviceIdentifier des, String config_string) package
Used to install the sound detector into the visualization.
Parameters
n the name of the sound detector
pos the PVector position of the sound detector in the sculpture
p the pin, UID identifier
parent_ the parent Node of this sound detector
des the DeviceIdentifier that stores the 2 char and 1 num identifier for this device e.g. SD1
config_string the configuration string that configures this device
Returns
none
Definition at line 112 of file SoundDetector.pde.
References DeviceIdentifier.device_number, elapsed_millis, gui, Sensor.installed, last_millis, my_level, Node.node_id, p_audio, p_envelope, parse_config_string(), VisGui.sd_levels, Sensor.uid, Sensor.virtual_depth, Sensor.virtual_height, and Sensor.virtual_width.
Referenced by Node.read_dl().
is_triggered()
SoundDetector.is_triggered () package
checks if the current reading is above the specified threshold
Returns
If the reading > threshold, return true. If reading < threshold return false.
Definition at line 174 of file SoundDetector.pde.
References readValue(), and threshold.
parse_config_string()
boolean SoundDetector.parse_config_string (String config_string) package
Definition at line 203 of file SoundDetector.pde.
References autosample, frequency, Sensor.get_command(), Sensor.get_num_commands(), p_audio, p_envelope, and threshold.
Referenced by install().
read_audio()
SoundDetector.read_audio () package
supposed to read the audio pin, currently just calls the readValue() function. Not really implemented yet.
Returns
an integer version of the readValue()
Definition at line 163 of file SoundDetector.pde.
References Sensor.cur_value, readme, and readValue().
read_envelope()
SoundDetector.read_envelope () package
supposed to read the envelope pin, currently just calls the readValue() function
Returns
an integer version of the readValue()
Definition at line 152 of file SoundDetector.pde.
References Sensor.cur_value, readme, and readValue().
readValue()
SoundDetector.readValue () package
returns the sound reading from your computer's mic
Returns
a float of the sound reading, on the conputer it reads your mic level
Definition at line 141 of file SoundDetector.pde.
References my_level.
Referenced by go(), is_triggered(), read_audio(), and read_envelope().
update()
SoundDetector.update () package
called to update the detector and check if its time for polling
Returns
none
Definition at line 185 of file SoundDetector.pde.
References autosample, elapsed_millis, frequency, last_millis, and readme.
Referenced by Node.run().
update_info()
SoundDetector.update_info () package
helper function to do drawing of visualization
Returns
none
Definition at line 300 of file SoundDetector.pde.
References apply_sd_settings_to(), autosample, Sensor.cur_value, frequency, gui, Sensor.name, Node.node_id, Sensor.parent, push_value, VisGui.sd_freq_slider, VisGui.sd_polling, VisGui.sd_settings, VisGui.sd_thresh_slider, VisGui.sdChart, selected_sensor, threshold, and VisGui.which_sds.
Member Data Documentation
autosample
SoundDetector.autosample = true package
Boolean to control if autosampling is on. True to turn on autosampling, false to turn it off
Definition at line 70 of file SoundDetector.pde.
Referenced by parse_config_string(), Node.run(), update(), and update_info().
DEFAULT_FREQ
SoundDetector.DEFAULT_FREQ = 50 package
The default polling frequency in hertz
Definition at line 23 of file SoundDetector.pde.
DEFAULT_THRESHOLD
SoundDetector.DEFAULT_THRESHOLD = 5 package
The default threshold to send back data if passed
Definition at line 18 of file SoundDetector.pde.
elapsed_millis
SoundDetector.elapsed_millis = 0 package
Used for timing to send back messages to control
Definition at line 64 of file SoundDetector.pde.
Referenced by install(), and update().
frequency
SoundDetector.frequency = DEFAULT_FREQ package
the active frequency of the sound detector for sending back data
Definition at line 46 of file SoundDetector.pde.
Referenced by parse_config_string(), Node.run(), update(), and update_info().
last_millis
SoundDetector.last_millis = millis() package
Used for timing to send back messages to control
Definition at line 58 of file SoundDetector.pde.
Referenced by install(), and update().
my_level
SoundDetector.my_level package
TODO
Definition at line 88 of file SoundDetector.pde.
Referenced by install(), and readValue().
p_audio
SoundDetector.p_audio = 0 package
the audio pin of the sound detector
Definition at line 34 of file SoundDetector.pde.
Referenced by install(), and parse_config_string().
p_envelope
SoundDetector.p_envelope = 0 package
the envelope pin of the sound detector
Definition at line 29 of file SoundDetector.pde.
Referenced by install(), and parse_config_string().
push_value
SoundDetector.push_value = false package
TODO
Definition at line 82 of file SoundDetector.pde.
Referenced by go(), and update_info().
readme
SoundDetector.readme = false package
tells the timing loop if its time to read the detector and send back data
Definition at line 52 of file SoundDetector.pde.
Referenced by go(), read_audio(), read_envelope(), and update().
threshold
SoundDetector.threshold = DEFAULT_THRESHOLD package
the active threshold of the sound detector
Definition at line 40 of file SoundDetector.pde.
Referenced by go(), is_triggered(), parse_config_string(), Node.run(), and update_info().
use_local
SoundDetector.use_local = false package
TODO
Definition at line 76 of file SoundDetector.pde.
Referenced by go().
The documentation for this class was generated from the following file:
SoundDetector.pde