Control_World: DoubleRebelStar Class Reference
DoubleRebelStar Class Reference
Package Functions
DoubleRebelStar ()
void install (String n, PVector pos, int pin, Node parent_, DeviceIdentifier des, String config_string)
void setValue (int v)
void fade (int v, long fade_millis)
synchronized void update ()
void go ()
boolean parse_config_string (String config)
void update_info ()
void draw_me (boolean mouseover)
Package Functions inherited from Actuator
Actuator ()
void install (String n, PVector pos, int pin, Node parent_, DeviceIdentifier des)
abstract void setValue (int v)
abstract void fade (int v, long fade_millis)
DInt setValue (int v, DInt cur_values)
DInt fade (int v, long fade_millis, DInt cur_values)
DInt update_DInt (DInt cur_values)
abstract void update ()
synchronized void go ()
synchronized void draw_to_screen ()
void draw_box ()
PVector [] getBox ()
boolean is_mouse_over ()
boolean containsPoint (PVector[] verts, float px, float py)
void draw_me (boolean mouseover)
void update_info ()
Package Attributes
int top_pin = 0
DInt top_value = new DInt()
int bottom_pin = 0
DInt bottom_value = new DInt()
Package Attributes inherited from Actuator
String name
DeviceIdentifier designator
int uid
int cur_value
boolean installed = false
int virtual_width
int virtual_height
int virtual_depth
PVector position
boolean selected = false
Node parent
Additional Inherited Members
Protected Member Functions inherited from Actuator
int get_num_commands (String str)
String get_full_command (String str, int num)
String [] get_command (String str, int num)
Detailed Description
DoubleRebelStar
Double Rebel Star object for visualization
Author
Matt Gorbet, Et al.
Definition at line 10 of file DoubleRebelStar.pde.
Constructor & Destructor Documentation
DoubleRebelStar()
DoubleRebelStar.DoubleRebelStar () package
Definition at line 18 of file DoubleRebelStar.pde.
Member Function Documentation
draw_me()
void DoubleRebelStar.draw_me (boolean mouseover) package
Definition at line 129 of file DoubleRebelStar.pde.
References ALL_NODES_SELECTED, bottom_value, Actuator.designator, DeviceIdentifier.device_type, drawgui, Node.node_id, Actuator.parent, selected_actuator, selected_node, DInt.state, top_value, Actuator.virtual_height, and Actuator.virtual_width.
fade()
void DoubleRebelStar.fade (int v, long fade_millis) package
Definition at line 45 of file DoubleRebelStar.pde.
References bottom_value, and top_value.
Referenced by Node.run(), and setValue().
go()
void DoubleRebelStar.go () package
Definition at line 61 of file DoubleRebelStar.pde.
Referenced by Node.go().
install()
void DoubleRebelStar.install (String n, PVector pos, int pin, Node parent_, DeviceIdentifier des, String config_string) package
Definition at line 23 of file DoubleRebelStar.pde.
References bottom_pin, bottom_value, DInt.fade_target, parse_config_string(), DInt.state, top_value, Actuator.virtual_depth, Actuator.virtual_height, and Actuator.virtual_width.
Referenced by Node.read_dl().
parse_config_string()
boolean DoubleRebelStar.parse_config_string (String config) package
Definition at line 68 of file DoubleRebelStar.pde.
References bottom_pin, Actuator.get_command(), Actuator.get_num_commands(), and top_pin.
Referenced by install().
setValue()
void DoubleRebelStar.setValue (int v) package
Definition at line 40 of file DoubleRebelStar.pde.
References fade().
update()
synchronized void DoubleRebelStar.update () package
Definition at line 54 of file DoubleRebelStar.pde.
References bottom_value, top_value, and Actuator.update_DInt().
Referenced by Node.run().
update_info()
void DoubleRebelStar.update_info () package
Definition at line 100 of file DoubleRebelStar.pde.
References VisGui.actuator_settings, VisGui.actuatorChart, apply_drs_settings_to(), bottom_value, VisGui.drs_settings, gui, Actuator.name, selected_actuator, DInt.state, top_value, and VisGui.which_drs.
Member Data Documentation
bottom_pin
int DoubleRebelStar.bottom_pin = 0 package
Definition at line 15 of file DoubleRebelStar.pde.
Referenced by install(), and parse_config_string().
bottom_value
DInt DoubleRebelStar.bottom_value = new DInt() package
Definition at line 16 of file DoubleRebelStar.pde.
Referenced by draw_me(), fade(), install(), update(), and update_info().
top_pin
int DoubleRebelStar.top_pin = 0 package
Definition at line 12 of file DoubleRebelStar.pde.
Referenced by parse_config_string().
top_value
DInt DoubleRebelStar.top_value = new DInt() package
Definition at line 13 of file DoubleRebelStar.pde.
Referenced by draw_me(), fade(), install(), update(), and update_info().
The documentation for this class was generated from the following file:
DoubleRebelStar.pde