Control_World: DeviceLocatorNodeStorage Class Reference
DeviceLocatorNodeStorage Class Reference
Package Functions
DeviceLocatorNodeStorage ()
synchronized boolean node_type_exists (String node_type)
synchronized String get_node_type (int node_id)
synchronized String get_uid_type (int uid, int node_id)
Package Attributes
ArrayList< Integer > node_ids = new ArrayList<Integer>()
ArrayList< String > node_types = new ArrayList<String>()
ListMultimap< String, Integer > all_uids = ArrayListMultimap.create()
ListMultimap< String, String > all_uid_types = ArrayListMultimap.create()
ListMultimap< Integer, String > all_names = ArrayListMultimap.create()
ListMultimap< Integer, PVector > all_coordinates = ArrayListMultimap.create()
ListMultimap< Integer, String > all_configs = ArrayListMultimap.create()
ListMultimap< Integer, Boolean > all_installed = ArrayListMultimap.create()
Detailed Description
This class stores information in Arrays similiar to how they are stored in the dot h files. This is to ensure we can make similar function calls in the processing and the C++.
Definition at line 976 of file DeviceLocator.pde.
Constructor & Destructor Documentation
DeviceLocatorNodeStorage()
DeviceLocatorNodeStorage.DeviceLocatorNodeStorage () package
Definition at line 990 of file DeviceLocator.pde.
Member Function Documentation
get_node_type()
synchronized String DeviceLocatorNodeStorage.get_node_type (int node_id) package
Definition at line 1004 of file DeviceLocator.pde.
References node_ids, and node_types.
Referenced by DeviceLocator.get_actuator_uid(), DeviceLocator.get_coordinates_for_type(), DeviceLocator.get_sensor_uid(), and get_uid_type().
get_uid_type()
synchronized String DeviceLocatorNodeStorage.get_uid_type (int uid, int node_id) package
Definition at line 1020 of file DeviceLocator.pde.
References all_uid_types, all_uids, and get_node_type().
node_type_exists()
synchronized boolean DeviceLocatorNodeStorage.node_type_exists (String node_type) package
Definition at line 994 of file DeviceLocator.pde.
References all_coordinates, all_uid_types, and all_uids.
Member Data Documentation
all_configs
ListMultimap<Integer, String> DeviceLocatorNodeStorage.all_configs = ArrayListMultimap.create() package
Definition at line 987 of file DeviceLocator.pde.
Referenced by DeviceLocator.add_device(), DeviceLocator.generate_dot_h(), and DeviceLocator.get_configs().
all_coordinates
ListMultimap<Integer, PVector> DeviceLocatorNodeStorage.all_coordinates = ArrayListMultimap.create() package
Definition at line 986 of file DeviceLocator.pde.
Referenced by DeviceLocator.add_device(), DeviceLocator.generate_dot_h(), DeviceLocator.get_coordinates(), DeviceLocator.get_coordinates_for_type(), and node_type_exists().
all_installed
ListMultimap<Integer, Boolean> DeviceLocatorNodeStorage.all_installed = ArrayListMultimap.create() package
Definition at line 988 of file DeviceLocator.pde.
Referenced by DeviceLocator.add_device(), and DeviceLocator.get_installed().
all_names
ListMultimap<Integer, String> DeviceLocatorNodeStorage.all_names = ArrayListMultimap.create() package
Definition at line 985 of file DeviceLocator.pde.
Referenced by DeviceLocator.add_device(), DeviceLocator.generate_dot_h(), and DeviceLocator.get_names().
all_uid_types
ListMultimap<String, String> DeviceLocatorNodeStorage.all_uid_types = ArrayListMultimap.create() package
Definition at line 984 of file DeviceLocator.pde.
Referenced by DeviceLocator.add_device(), DeviceLocator.get_coordinates_for_type(), DeviceLocator.get_types(), get_uid_type(), and node_type_exists().
all_uids
ListMultimap<String, Integer> DeviceLocatorNodeStorage.all_uids = ArrayListMultimap.create() package
Definition at line 983 of file DeviceLocator.pde.
Referenced by DeviceLocator.add_device(), DeviceLocator.get_actuator_uid(), DeviceLocator.get_sensor_uid(), get_uid_type(), DeviceLocator.get_uids(), and node_type_exists().
node_ids
ArrayList<Integer> DeviceLocatorNodeStorage.node_ids = new ArrayList<Integer>() package
Definition at line 980 of file DeviceLocator.pde.
Referenced by DeviceLocator.add_node(), DeviceLocator.generate_dot_h(), DeviceLocator.generate_dot_hexmap(), DeviceLocator.get_node_ids(), DeviceLocator.get_node_type(), get_node_type(), DeviceLocator.get_num_nodes(), DeviceLocator.node_exists(), and DeviceLocator.node_present().
node_types
ArrayList<String> DeviceLocatorNodeStorage.node_types = new ArrayList<String>() package
Definition at line 981 of file DeviceLocator.pde.
Referenced by DeviceLocator.add_node(), DeviceLocator.generate_dot_h(), DeviceLocator.generate_dot_hexmap(), DeviceLocator.get_node_type(), and get_node_type().
The documentation for this class was generated from the following file:
DeviceLocator.pde