Control_World: External_Comms Class Reference
External_Comms Class Reference
used for external communication
Package Functions
External_Comms (String ip_control)
Constructor for the external comms manager.
synchronized void write_message (message_OSC message_in)
write an OSC message to the external comms agent
synchronized void osc_received (OscMessage received_message)
helped function called by the listener in Control_World.pde to store the incoming message
synchronized message_OSC get_message ()
get the message
Package Attributes
String addr_control = ""
String addr_ext = ""
int port_ext = 3001
message_OSC real_received_message = null
Detailed Description
used for external communication
External_Comms
messaging object for external communication
Author
Farhan Monower
Definition at line 13 of file External_Comms.pde.
Constructor & Destructor Documentation
External_Comms()
External_Comms.External_Comms (String ip_control) package
Constructor for the external comms manager.
Parameters
ip_control the ip address of the control device
Returns
none
Definition at line 44 of file External_Comms.pde.
References initialize_external_osc(), and port_ext.
Member Function Documentation
get_message()
External_Comms.get_message () package
get the message
Returns
message_OSC of the message contained in external comms
Definition at line 79 of file External_Comms.pde.
References real_received_message.
Referenced by Control.run().
osc_received()
External_Comms.osc_received (OscMessage received_message) package
helped function called by the listener in Control_World.pde to store the incoming message
Parameters
received_message the received message
Returns
none
Definition at line 67 of file External_Comms.pde.
References message_OSC.get_data().
write_message()
External_Comms.write_message (message_OSC message_in) package
write an OSC message to the external comms agent
Parameters
message_in the message to send
Returns
none
Definition at line 55 of file External_Comms.pde.
References addr_ext, external_osc, message_OSC.get_OSC(), and port_ext.
Member Data Documentation
addr_control
External_Comms.addr_control = "" package
address of control, gets set automatically
Definition at line 18 of file External_Comms.pde.
addr_ext
External_Comms.addr_ext = "" package
address of the external agent, currently needs to get set manually in the World Builder
Definition at line 24 of file External_Comms.pde.
Referenced by write_message().
port_ext
External_Comms.port_ext = 3001 package
the port of the external agent, also needs to get set manually or standardized and hard-coded
Definition at line 30 of file External_Comms.pde.
Referenced by External_Comms(), and write_message().
real_received_message
External_Comms.real_received_message = null package
holds the last received real message from the external agent
Definition at line 36 of file External_Comms.pde.
Referenced by get_message().
The documentation for this class was generated from the following file:
External_Comms.pde