Control_World: MessageCodes
MessageCodes
Variables
int CODE__SET_ACTUATOR_VALUES = int(0x1a)
int CODE__SOUND_PT_SAMPLING_CONTROL = int(0x2a)
int CODE__SOUND_PT_SAMPLING_RPI = int(0x2b)
int CODE__SOUND_AUTO_SAMPLING = int(0x2c)
int CODE__SOUND_SET_THRESHOLD = int(0x2d)
int CODE__SOUND_SET_SAMPLE_FREQUENCY = int(0x2e)
int CODE__WAV_PLAY_SOUND = int(0x1b)
int CODE__WAV_MASTER_GAIN = int(0x1c)
int CODE__WAV_TRACK_GAIN = int(0x1d)
int CODE__WAV_TRACK_FADE = int(0x1e)
int CODE__WAV_MASTER_STOP = int(0x1f)
int CODE__INFLUENCE_MAP_GP = int(0Xb1)
int CODE__INFLUENCE_MAP_GM = int(0Xb2)
int CODE__INFLUENCE_MAP_SD = int(0Xb3)
int CODE__INFLUENCE_RANGE_GP = int(0xc1)
int CODE__INFLUENCE_RANGE_GM = int(0xc2)
int CODE__INFLUENCE_RANGE_SD = int(0xc3)
int CODE__INFLUENCE_RANGE_EXP = int(0xc4)
int CODE__INFLUENCE_RANGE_EXM = int(0xc5)
int CODE__INFLUENCE_RANGE_EXS = int(0xc6)
int CODE__PASSWORD = int(0xaa)
boolean Comm_Manager.debug = false
boolean Comm_Manager.use_wifi = false
int Comm_Manager.osc_port = 4000
int Comm_Manager.grideye_live_port = 5445
int Comm_Manager.password_reply_length = 12
int Comm_Manager.poll_length = 100
int Comm_Manager.ports_timeout_time = 10000
int Comm_Manager.serial_port_limit = 64
Detailed Description
defines message codes used in serial and osc communication between control, pis and nodes
Variable Documentation
CODE__INFLUENCE_MAP_GM
int CODE__INFLUENCE_MAP_GM = int(0Xb2) package
import "Comm_Manager.pde"
Definition at line 59 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__INFLUENCE_MAP_GP
int CODE__INFLUENCE_MAP_GP = int(0Xb1) package
import "Comm_Manager.pde"
Influence map and range codes
Definition at line 58 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__INFLUENCE_MAP_SD
int CODE__INFLUENCE_MAP_SD = int(0Xb3) package
import "Comm_Manager.pde"
Definition at line 60 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__INFLUENCE_RANGE_EXM
int CODE__INFLUENCE_RANGE_EXM = int(0xc5) package
import "Comm_Manager.pde"
Definition at line 65 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__INFLUENCE_RANGE_EXP
int CODE__INFLUENCE_RANGE_EXP = int(0xc4) package
import "Comm_Manager.pde"
Definition at line 64 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__INFLUENCE_RANGE_EXS
int CODE__INFLUENCE_RANGE_EXS = int(0xc6) package
import "Comm_Manager.pde"
Definition at line 66 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__INFLUENCE_RANGE_GM
int CODE__INFLUENCE_RANGE_GM = int(0xc2) package
import "Comm_Manager.pde"
Definition at line 62 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__INFLUENCE_RANGE_GP
int CODE__INFLUENCE_RANGE_GP = int(0xc1) package
import "Comm_Manager.pde"
Definition at line 61 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__INFLUENCE_RANGE_SD
int CODE__INFLUENCE_RANGE_SD = int(0xc3) package
import "Comm_Manager.pde"
Definition at line 63 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__PASSWORD
int CODE__PASSWORD = int(0xaa) package
import "Comm_Manager.pde"
password used in hanshaking
Definition at line 70 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_password_to_port().
CODE__SET_ACTUATOR_VALUES
int CODE__SET_ACTUATOR_VALUES = int(0x1a) package
import "Comm_Manager.pde"
used by FADE_ACTUATOR_VALUES to set actuator levels
Definition at line 37 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__SOUND_AUTO_SAMPLING
int CODE__SOUND_AUTO_SAMPLING = int(0x2c) package
import "Comm_Manager.pde"
Definition at line 43 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__SOUND_PT_SAMPLING_CONTROL
int CODE__SOUND_PT_SAMPLING_CONTROL = int(0x2a) package
import "Comm_Manager.pde"
Sound sensor codes
Definition at line 41 of file Comm_Manager.pde.
Referenced by Comm_Manager.get_message_real(), and Comm_Manager.write_message().
CODE__SOUND_PT_SAMPLING_RPI
int CODE__SOUND_PT_SAMPLING_RPI = int(0x2b) package
import "Comm_Manager.pde"
Definition at line 42 of file Comm_Manager.pde.
Referenced by Comm_Manager.get_message_real(), and Comm_Manager.write_message().
CODE__SOUND_SET_SAMPLE_FREQUENCY
int CODE__SOUND_SET_SAMPLE_FREQUENCY = int(0x2e) package
import "Comm_Manager.pde"
Definition at line 45 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__SOUND_SET_THRESHOLD
int CODE__SOUND_SET_THRESHOLD = int(0x2d) package
import "Comm_Manager.pde"
Definition at line 44 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__WAV_MASTER_GAIN
int CODE__WAV_MASTER_GAIN = int(0x1c) package
import "Comm_Manager.pde"
Definition at line 50 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__WAV_MASTER_STOP
int CODE__WAV_MASTER_STOP = int(0x1f) package
import "Comm_Manager.pde"
Definition at line 53 of file Comm_Manager.pde.
CODE__WAV_PLAY_SOUND
int CODE__WAV_PLAY_SOUND = int(0x1b) package
import "Comm_Manager.pde"
WAV Trigger codes
Definition at line 49 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__WAV_TRACK_FADE
int CODE__WAV_TRACK_FADE = int(0x1e) package
import "Comm_Manager.pde"
Definition at line 52 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
CODE__WAV_TRACK_GAIN
int CODE__WAV_TRACK_GAIN = int(0x1d) package
import "Comm_Manager.pde"
Definition at line 51 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
debug
boolean Comm_Manager.debug = false package
used to do printlns
Definition at line 130 of file Comm_Manager.pde.
Referenced by keyPressed().
grideye_live_port
int Comm_Manager.grideye_live_port = 5445 package
Definition at line 140 of file Comm_Manager.pde.
Referenced by GridEye.update_info().
osc_port
int Comm_Manager.osc_port = 4000 package
port allocation
Definition at line 139 of file Comm_Manager.pde.
Referenced by Comm_Manager.Comm_Manager().
password_reply_length
int Comm_Manager.password_reply_length = 12 package
variables used in handshaking
Definition at line 145 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_password_to_port().
poll_length
int Comm_Manager.poll_length = 100 package
Definition at line 146 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_password_to_port().
ports_timeout_time
int Comm_Manager.ports_timeout_time = 10000 package
Definition at line 147 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_password_to_port().
serial_port_limit
int Comm_Manager.serial_port_limit = 64 package
Definition at line 148 of file Comm_Manager.pde.
Referenced by Comm_Manager.write_message().
use_wifi
boolean Comm_Manager.use_wifi = false package
tells comm manager to use the ethernet or the wifi ip address
Definition at line 135 of file Comm_Manager.pde.
Referenced by Comm_Manager.Comm_Manager(), and setup().